package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Compstructtree generated by hbm2java
 */
@Entity
@Table(name="compstructtree"
    ,catalog="ashrm"
)
public class Compstructtree  implements java.io.Serializable {


     private int id;
     private Location location;
     private String title;
     private String description;
     private int lft;
     private int rgt;
     private int parnt;
     private String deptId;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Compstructtree() {
    }

	
    public Compstructtree(int id, String title, String description, int lft, int rgt, int parnt) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.lft = lft;
        this.rgt = rgt;
        this.parnt = parnt;
    }
    public Compstructtree(int id, Location location, String title, String description, int lft, int rgt, int parnt, String deptId, Set<Employee> employees) {
       this.id = id;
       this.location = location;
       this.title = title;
       this.description = description;
       this.lft = lft;
       this.rgt = rgt;
       this.parnt = parnt;
       this.deptId = deptId;
       this.employees = employees;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loc_code")
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="lft", nullable=false)
    public int getLft() {
        return this.lft;
    }
    
    public void setLft(int lft) {
        this.lft = lft;
    }
    
    @Column(name="rgt", nullable=false)
    public int getRgt() {
        return this.rgt;
    }
    
    public void setRgt(int rgt) {
        this.rgt = rgt;
    }
    
    @Column(name="parnt", nullable=false)
    public int getParnt() {
        return this.parnt;
    }
    
    public void setParnt(int parnt) {
        this.parnt = parnt;
    }
    
    @Column(name="dept_id", length=32)
    public String getDeptId() {
        return this.deptId;
    }
    
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="compstructtree")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


