package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CurrencyType generated by hbm2java
 */
@Entity
@Table(name="currency_type"
    ,catalog="ashrm"
)
public class CurrencyType  implements java.io.Serializable {


     private String currencyId;
     private int code;
     private String currencyName;
     private Set<EmpBasicsalary> empBasicsalaries = new HashSet<EmpBasicsalary>(0);
     private Set<HsPrSalaryCurrencyDetail> hsPrSalaryCurrencyDetails = new HashSet<HsPrSalaryCurrencyDetail>(0);

    public CurrencyType() {
    }

	
    public CurrencyType(String currencyId, int code, String currencyName) {
        this.currencyId = currencyId;
        this.code = code;
        this.currencyName = currencyName;
    }
    public CurrencyType(String currencyId, int code, String currencyName, Set<EmpBasicsalary> empBasicsalaries, Set<HsPrSalaryCurrencyDetail> hsPrSalaryCurrencyDetails) {
       this.currencyId = currencyId;
       this.code = code;
       this.currencyName = currencyName;
       this.empBasicsalaries = empBasicsalaries;
       this.hsPrSalaryCurrencyDetails = hsPrSalaryCurrencyDetails;
    }
   
     @Id 
    
    @Column(name="currency_id", unique=true, nullable=false, length=3)
    public String getCurrencyId() {
        return this.currencyId;
    }
    
    public void setCurrencyId(String currencyId) {
        this.currencyId = currencyId;
    }
    
    @Column(name="code", nullable=false)
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    
    @Column(name="currency_name", nullable=false, length=70)
    public String getCurrencyName() {
        return this.currencyName;
    }
    
    public void setCurrencyName(String currencyName) {
        this.currencyName = currencyName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="currencyType")
    public Set<EmpBasicsalary> getEmpBasicsalaries() {
        return this.empBasicsalaries;
    }
    
    public void setEmpBasicsalaries(Set<EmpBasicsalary> empBasicsalaries) {
        this.empBasicsalaries = empBasicsalaries;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="currencyType")
    public Set<HsPrSalaryCurrencyDetail> getHsPrSalaryCurrencyDetails() {
        return this.hsPrSalaryCurrencyDetails;
    }
    
    public void setHsPrSalaryCurrencyDetails(Set<HsPrSalaryCurrencyDetail> hsPrSalaryCurrencyDetails) {
        this.hsPrSalaryCurrencyDetails = hsPrSalaryCurrencyDetails;
    }




}


