package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomExport generated by hbm2java
 */
@Entity
@Table(name="custom_export"
    ,catalog="ashrm"
)
public class CustomExport  implements java.io.Serializable {


     private int exportId;
     private String name;
     private String fields;
     private String headings;

    public CustomExport() {
    }

	
    public CustomExport(int exportId, String name) {
        this.exportId = exportId;
        this.name = name;
    }
    public CustomExport(int exportId, String name, String fields, String headings) {
       this.exportId = exportId;
       this.name = name;
       this.fields = fields;
       this.headings = headings;
    }
   
     @Id 
    
    @Column(name="export_id", unique=true, nullable=false)
    public int getExportId() {
        return this.exportId;
    }
    
    public void setExportId(int exportId) {
        this.exportId = exportId;
    }
    
    @Column(name="name", nullable=false, length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="fields", length=65535)
    public String getFields() {
        return this.fields;
    }
    
    public void setFields(String fields) {
        this.fields = fields;
    }
    
    @Column(name="headings", length=65535)
    public String getHeadings() {
        return this.headings;
    }
    
    public void setHeadings(String headings) {
        this.headings = headings;
    }




}


