package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomImport generated by hbm2java
 */
@Entity
@Table(name="custom_import"
    ,catalog="ashrm"
)
public class CustomImport  implements java.io.Serializable {


     private int importId;
     private String name;
     private String fields;
     private Boolean hasHeading;

    public CustomImport() {
    }

	
    public CustomImport(int importId, String name) {
        this.importId = importId;
        this.name = name;
    }
    public CustomImport(int importId, String name, String fields, Boolean hasHeading) {
       this.importId = importId;
       this.name = name;
       this.fields = fields;
       this.hasHeading = hasHeading;
    }
   
     @Id 
    
    @Column(name="import_id", unique=true, nullable=false)
    public int getImportId() {
        return this.importId;
    }
    
    public void setImportId(int importId) {
        this.importId = importId;
    }
    
    @Column(name="name", nullable=false, length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="fields", length=65535)
    public String getFields() {
        return this.fields;
    }
    
    public void setFields(String fields) {
        this.fields = fields;
    }
    
    @Column(name="has_heading")
    public Boolean getHasHeading() {
        return this.hasHeading;
    }
    
    public void setHasHeading(Boolean hasHeading) {
        this.hasHeading = hasHeading;
    }




}


