package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomFields generated by hbm2java
 */
@Entity
@Table(name="custom_fields"
    ,catalog="ashrm"
)
public class CustomFields  implements java.io.Serializable {


     private int fieldNum;
     private String name;
     private int type;
     private String extraData;

    public CustomFields() {
    }

	
    public CustomFields(int fieldNum, String name, int type) {
        this.fieldNum = fieldNum;
        this.name = name;
        this.type = type;
    }
    public CustomFields(int fieldNum, String name, int type, String extraData) {
       this.fieldNum = fieldNum;
       this.name = name;
       this.type = type;
       this.extraData = extraData;
    }
   
     @Id 
    
    @Column(name="field_num", unique=true, nullable=false)
    public int getFieldNum() {
        return this.fieldNum;
    }
    
    public void setFieldNum(int fieldNum) {
        this.fieldNum = fieldNum;
    }
    
    @Column(name="name", nullable=false, length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="type", nullable=false)
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    
    @Column(name="extra_data", length=250)
    public String getExtraData() {
        return this.extraData;
    }
    
    public void setExtraData(String extraData) {
        this.extraData = extraData;
    }




}


