package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name="district"
    ,catalog="ashrm"
)
public class District  implements java.io.Serializable {


     private String districtCode;
     private String districtName;
     private String provinceCode;

    public District() {
    }

	
    public District(String districtCode) {
        this.districtCode = districtCode;
    }
    public District(String districtCode, String districtName, String provinceCode) {
       this.districtCode = districtCode;
       this.districtName = districtName;
       this.provinceCode = provinceCode;
    }
   
     @Id 
    
    @Column(name="district_code", unique=true, nullable=false, length=13)
    public String getDistrictCode() {
        return this.districtCode;
    }
    
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }
    
    @Column(name="district_name", length=50)
    public String getDistrictName() {
        return this.districtName;
    }
    
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }
    
    @Column(name="province_code", length=13)
    public String getProvinceCode() {
        return this.provinceCode;
    }
    
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }




}


