package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Eec generated by hbm2java
 */
@Entity
@Table(name="eec"
    ,catalog="ashrm"
)
public class Eec  implements java.io.Serializable {


     private String eecCode;
     private String eecDesc;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Eec() {
    }

	
    public Eec(String eecCode) {
        this.eecCode = eecCode;
    }
    public Eec(String eecCode, String eecDesc, Set<Employee> employees) {
       this.eecCode = eecCode;
       this.eecDesc = eecDesc;
       this.employees = employees;
    }
   
     @Id 
    
    @Column(name="eec_code", unique=true, nullable=false, length=13)
    public String getEecCode() {
        return this.eecCode;
    }
    
    public void setEecCode(String eecCode) {
        this.eecCode = eecCode;
    }
    
    @Column(name="eec_desc", length=50)
    public String getEecDesc() {
        return this.eecDesc;
    }
    
    public void setEecDesc(String eecDesc) {
        this.eecDesc = eecDesc;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="eec")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


