package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpAttachmentId generated by hbm2java
 */
@Embeddable
public class EmpAttachmentId  implements java.io.Serializable {


     private int empNumber;
     private long eattachId;

    public EmpAttachmentId() {
    }

    public EmpAttachmentId(int empNumber, long eattachId) {
       this.empNumber = empNumber;
       this.eattachId = eattachId;
    }
   

    @Column(name="emp_number", nullable=false)
    public int getEmpNumber() {
        return this.empNumber;
    }
    
    public void setEmpNumber(int empNumber) {
        this.empNumber = empNumber;
    }

    @Column(name="eattach_id", nullable=false, precision=10, scale=0)
    public long getEattachId() {
        return this.eattachId;
    }
    
    public void setEattachId(long eattachId) {
        this.eattachId = eattachId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpAttachmentId) ) return false;
		 EmpAttachmentId castOther = ( EmpAttachmentId ) other; 
         
		 return (this.getEmpNumber()==castOther.getEmpNumber())
 && (this.getEattachId()==castOther.getEattachId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpNumber();
         result = 37 * result + (int) this.getEattachId();
         return result;
   }   


}


