package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpBasicsalary generated by hbm2java
 */
@Entity
@Table(name="emp_basicsalary"
    ,catalog="ashrm"
)
public class EmpBasicsalary  implements java.io.Serializable {


     private EmpBasicsalaryId id;
     private Salarygrade salarygrade;
     private CurrencyType currencyType;
     private Payperiod payperiod;
     private Employee employee;
     private String ebsalBasicSalary;

    public EmpBasicsalary() {
    }

	
    public EmpBasicsalary(EmpBasicsalaryId id, Salarygrade salarygrade, CurrencyType currencyType, Employee employee) {
        this.id = id;
        this.salarygrade = salarygrade;
        this.currencyType = currencyType;
        this.employee = employee;
    }
    public EmpBasicsalary(EmpBasicsalaryId id, Salarygrade salarygrade, CurrencyType currencyType, Payperiod payperiod, Employee employee, String ebsalBasicSalary) {
       this.id = id;
       this.salarygrade = salarygrade;
       this.currencyType = currencyType;
       this.payperiod = payperiod;
       this.employee = employee;
       this.ebsalBasicSalary = ebsalBasicSalary;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="salGrdCode", column=@Column(name="sal_grd_code", nullable=false, length=13) ), 
        @AttributeOverride(name="currencyId", column=@Column(name="currency_id", nullable=false, length=3) ) } )
    public EmpBasicsalaryId getId() {
        return this.id;
    }
    
    public void setId(EmpBasicsalaryId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sal_grd_code", nullable=false, insertable=false, updatable=false)
    public Salarygrade getSalarygrade() {
        return this.salarygrade;
    }
    
    public void setSalarygrade(Salarygrade salarygrade) {
        this.salarygrade = salarygrade;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="currency_id", nullable=false, insertable=false, updatable=false)
    public CurrencyType getCurrencyType() {
        return this.currencyType;
    }
    
    public void setCurrencyType(CurrencyType currencyType) {
        this.currencyType = currencyType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="payperiod_code")
    public Payperiod getPayperiod() {
        return this.payperiod;
    }
    
    public void setPayperiod(Payperiod payperiod) {
        this.payperiod = payperiod;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    @Column(name="ebsal_basic_salary", length=100)
    public String getEbsalBasicSalary() {
        return this.ebsalBasicSalary;
    }
    
    public void setEbsalBasicSalary(String ebsalBasicSalary) {
        this.ebsalBasicSalary = ebsalBasicSalary;
    }




}


