package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpContractExtend generated by hbm2java
 */
@Entity
@Table(name="emp_contract_extend"
    ,catalog="ashrm"
)
public class EmpContractExtend  implements java.io.Serializable {


     private EmpContractExtendId id;
     private Employee employee;
     private Date econExtendStartDate;
     private Date econExtendEndDate;

    public EmpContractExtend() {
    }

	
    public EmpContractExtend(EmpContractExtendId id, Employee employee) {
        this.id = id;
        this.employee = employee;
    }
    public EmpContractExtend(EmpContractExtendId id, Employee employee, Date econExtendStartDate, Date econExtendEndDate) {
       this.id = id;
       this.employee = employee;
       this.econExtendStartDate = econExtendStartDate;
       this.econExtendEndDate = econExtendEndDate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="econExtendId", column=@Column(name="econ_extend_id", nullable=false, precision=10, scale=0) ) } )
    public EmpContractExtendId getId() {
        return this.id;
    }
    
    public void setId(EmpContractExtendId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="econ_extend_start_date", length=19)
    public Date getEconExtendStartDate() {
        return this.econExtendStartDate;
    }
    
    public void setEconExtendStartDate(Date econExtendStartDate) {
        this.econExtendStartDate = econExtendStartDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="econ_extend_end_date", length=19)
    public Date getEconExtendEndDate() {
        return this.econExtendEndDate;
    }
    
    public void setEconExtendEndDate(Date econExtendEndDate) {
        this.econExtendEndDate = econExtendEndDate;
    }




}


