package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpChildren generated by hbm2java
 */
@Entity
@Table(name="emp_children"
    ,catalog="ashrm"
)
public class EmpChildren  implements java.io.Serializable {


     private EmpChildrenId id;
     private Employee employee;
     private String ecName;
     private Date ecDateOfBirth;

    public EmpChildren() {
    }

	
    public EmpChildren(EmpChildrenId id, Employee employee) {
        this.id = id;
        this.employee = employee;
    }
    public EmpChildren(EmpChildrenId id, Employee employee, String ecName, Date ecDateOfBirth) {
       this.id = id;
       this.employee = employee;
       this.ecName = ecName;
       this.ecDateOfBirth = ecDateOfBirth;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="ecSeqno", column=@Column(name="ec_seqno", nullable=false, precision=2, scale=0) ) } )
    public EmpChildrenId getId() {
        return this.id;
    }
    
    public void setId(EmpChildrenId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    @Column(name="ec_name", length=100)
    public String getEcName() {
        return this.ecName;
    }
    
    public void setEcName(String ecName) {
        this.ecName = ecName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="ec_date_of_birth", length=10)
    public Date getEcDateOfBirth() {
        return this.ecDateOfBirth;
    }
    
    public void setEcDateOfBirth(Date ecDateOfBirth) {
        this.ecDateOfBirth = ecDateOfBirth;
    }




}


