package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpChildrenId generated by hbm2java
 */
@Embeddable
public class EmpChildrenId  implements java.io.Serializable {


     private int empNumber;
     private byte ecSeqno;

    public EmpChildrenId() {
    }

    public EmpChildrenId(int empNumber, byte ecSeqno) {
       this.empNumber = empNumber;
       this.ecSeqno = ecSeqno;
    }
   

    @Column(name="emp_number", nullable=false)
    public int getEmpNumber() {
        return this.empNumber;
    }
    
    public void setEmpNumber(int empNumber) {
        this.empNumber = empNumber;
    }

    @Column(name="ec_seqno", nullable=false, precision=2, scale=0)
    public byte getEcSeqno() {
        return this.ecSeqno;
    }
    
    public void setEcSeqno(byte ecSeqno) {
        this.ecSeqno = ecSeqno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpChildrenId) ) return false;
		 EmpChildrenId castOther = ( EmpChildrenId ) other; 
         
		 return (this.getEmpNumber()==castOther.getEmpNumber())
 && (this.getEcSeqno()==castOther.getEcSeqno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpNumber();
         result = 37 * result + this.getEcSeqno();
         return result;
   }   


}


