package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpContractExtendId generated by hbm2java
 */
@Embeddable
public class EmpContractExtendId  implements java.io.Serializable {


     private int empNumber;
     private long econExtendId;

    public EmpContractExtendId() {
    }

    public EmpContractExtendId(int empNumber, long econExtendId) {
       this.empNumber = empNumber;
       this.econExtendId = econExtendId;
    }
   

    @Column(name="emp_number", nullable=false)
    public int getEmpNumber() {
        return this.empNumber;
    }
    
    public void setEmpNumber(int empNumber) {
        this.empNumber = empNumber;
    }

    @Column(name="econ_extend_id", nullable=false, precision=10, scale=0)
    public long getEconExtendId() {
        return this.econExtendId;
    }
    
    public void setEconExtendId(long econExtendId) {
        this.econExtendId = econExtendId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpContractExtendId) ) return false;
		 EmpContractExtendId castOther = ( EmpContractExtendId ) other; 
         
		 return (this.getEmpNumber()==castOther.getEmpNumber())
 && (this.getEconExtendId()==castOther.getEconExtendId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpNumber();
         result = 37 * result + (int) this.getEconExtendId();
         return result;
   }   


}


