package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpDependents generated by hbm2java
 */
@Entity
@Table(name="emp_dependents"
    ,catalog="ashrm"
)
public class EmpDependents  implements java.io.Serializable {


     private EmpDependentsId id;
     private Employee employee;
     private String edName;
     private String edRelationship;

    public EmpDependents() {
    }

	
    public EmpDependents(EmpDependentsId id, Employee employee) {
        this.id = id;
        this.employee = employee;
    }
    public EmpDependents(EmpDependentsId id, Employee employee, String edName, String edRelationship) {
       this.id = id;
       this.employee = employee;
       this.edName = edName;
       this.edRelationship = edRelationship;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="edSeqno", column=@Column(name="ed_seqno", nullable=false, precision=2, scale=0) ) } )
    public EmpDependentsId getId() {
        return this.id;
    }
    
    public void setId(EmpDependentsId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    @Column(name="ed_name", length=100)
    public String getEdName() {
        return this.edName;
    }
    
    public void setEdName(String edName) {
        this.edName = edName;
    }
    
    @Column(name="ed_relationship", length=100)
    public String getEdRelationship() {
        return this.edRelationship;
    }
    
    public void setEdRelationship(String edRelationship) {
        this.edRelationship = edRelationship;
    }




}


