package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpDirectdebitId generated by hbm2java
 */
@Embeddable
public class EmpDirectdebitId  implements java.io.Serializable {


     private int empNumber;
     private byte ddSeqno;

    public EmpDirectdebitId() {
    }

    public EmpDirectdebitId(int empNumber, byte ddSeqno) {
       this.empNumber = empNumber;
       this.ddSeqno = ddSeqno;
    }
   

    @Column(name="emp_number", nullable=false)
    public int getEmpNumber() {
        return this.empNumber;
    }
    
    public void setEmpNumber(int empNumber) {
        this.empNumber = empNumber;
    }

    @Column(name="dd_seqno", nullable=false, precision=2, scale=0)
    public byte getDdSeqno() {
        return this.ddSeqno;
    }
    
    public void setDdSeqno(byte ddSeqno) {
        this.ddSeqno = ddSeqno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpDirectdebitId) ) return false;
		 EmpDirectdebitId castOther = ( EmpDirectdebitId ) other; 
         
		 return (this.getEmpNumber()==castOther.getEmpNumber())
 && (this.getDdSeqno()==castOther.getDdSeqno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpNumber();
         result = 37 * result + this.getDdSeqno();
         return result;
   }   


}


