package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpDirectdebit generated by hbm2java
 */
@Entity
@Table(name="emp_directdebit"
    ,catalog="ashrm"
)
public class EmpDirectdebit  implements java.io.Serializable {


     private EmpDirectdebitId id;
     private Employee employee;
     private int ddRoutingNum;
     private String ddAccount;
     private BigDecimal ddAmount;
     private String ddAccountType;
     private String ddTransactionType;

    public EmpDirectdebit() {
    }

    public EmpDirectdebit(EmpDirectdebitId id, Employee employee, int ddRoutingNum, String ddAccount, BigDecimal ddAmount, String ddAccountType, String ddTransactionType) {
       this.id = id;
       this.employee = employee;
       this.ddRoutingNum = ddRoutingNum;
       this.ddAccount = ddAccount;
       this.ddAmount = ddAmount;
       this.ddAccountType = ddAccountType;
       this.ddTransactionType = ddTransactionType;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="ddSeqno", column=@Column(name="dd_seqno", nullable=false, precision=2, scale=0) ) } )
    public EmpDirectdebitId getId() {
        return this.id;
    }
    
    public void setId(EmpDirectdebitId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    @Column(name="dd_routing_num", nullable=false)
    public int getDdRoutingNum() {
        return this.ddRoutingNum;
    }
    
    public void setDdRoutingNum(int ddRoutingNum) {
        this.ddRoutingNum = ddRoutingNum;
    }
    
    @Column(name="dd_account", nullable=false, length=100)
    public String getDdAccount() {
        return this.ddAccount;
    }
    
    public void setDdAccount(String ddAccount) {
        this.ddAccount = ddAccount;
    }
    
    @Column(name="dd_amount", nullable=false, precision=11)
    public BigDecimal getDdAmount() {
        return this.ddAmount;
    }
    
    public void setDdAmount(BigDecimal ddAmount) {
        this.ddAmount = ddAmount;
    }
    
    @Column(name="dd_account_type", nullable=false, length=20)
    public String getDdAccountType() {
        return this.ddAccountType;
    }
    
    public void setDdAccountType(String ddAccountType) {
        this.ddAccountType = ddAccountType;
    }
    
    @Column(name="dd_transaction_type", nullable=false, length=20)
    public String getDdTransactionType() {
        return this.ddTransactionType;
    }
    
    public void setDdTransactionType(String ddTransactionType) {
        this.ddTransactionType = ddTransactionType;
    }




}


