package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpEmergencyContacts generated by hbm2java
 */
@Entity
@Table(name="emp_emergency_contacts"
    ,catalog="ashrm"
)
public class EmpEmergencyContacts  implements java.io.Serializable {


     private EmpEmergencyContactsId id;
     private Employee employee;
     private String eecName;
     private String eecRelationship;
     private String eecHomeNo;
     private String eecMobileNo;
     private String eecOfficeNo;

    public EmpEmergencyContacts() {
    }

	
    public EmpEmergencyContacts(EmpEmergencyContactsId id, Employee employee) {
        this.id = id;
        this.employee = employee;
    }
    public EmpEmergencyContacts(EmpEmergencyContactsId id, Employee employee, String eecName, String eecRelationship, String eecHomeNo, String eecMobileNo, String eecOfficeNo) {
       this.id = id;
       this.employee = employee;
       this.eecName = eecName;
       this.eecRelationship = eecRelationship;
       this.eecHomeNo = eecHomeNo;
       this.eecMobileNo = eecMobileNo;
       this.eecOfficeNo = eecOfficeNo;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="eecSeqno", column=@Column(name="eec_seqno", nullable=false, precision=2, scale=0) ) } )
    public EmpEmergencyContactsId getId() {
        return this.id;
    }
    
    public void setId(EmpEmergencyContactsId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    @Column(name="eec_name", length=100)
    public String getEecName() {
        return this.eecName;
    }
    
    public void setEecName(String eecName) {
        this.eecName = eecName;
    }
    
    @Column(name="eec_relationship", length=100)
    public String getEecRelationship() {
        return this.eecRelationship;
    }
    
    public void setEecRelationship(String eecRelationship) {
        this.eecRelationship = eecRelationship;
    }
    
    @Column(name="eec_home_no", length=100)
    public String getEecHomeNo() {
        return this.eecHomeNo;
    }
    
    public void setEecHomeNo(String eecHomeNo) {
        this.eecHomeNo = eecHomeNo;
    }
    
    @Column(name="eec_mobile_no", length=100)
    public String getEecMobileNo() {
        return this.eecMobileNo;
    }
    
    public void setEecMobileNo(String eecMobileNo) {
        this.eecMobileNo = eecMobileNo;
    }
    
    @Column(name="eec_office_no", length=100)
    public String getEecOfficeNo() {
        return this.eecOfficeNo;
    }
    
    public void setEecOfficeNo(String eecOfficeNo) {
        this.eecOfficeNo = eecOfficeNo;
    }




}


