package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpEducationId generated by hbm2java
 */
@Embeddable
public class EmpEducationId  implements java.io.Serializable {


     private String eduCode;
     private int empNumber;

    public EmpEducationId() {
    }

    public EmpEducationId(String eduCode, int empNumber) {
       this.eduCode = eduCode;
       this.empNumber = empNumber;
    }
   

    @Column(name="edu_code", nullable=false, length=13)
    public String getEduCode() {
        return this.eduCode;
    }
    
    public void setEduCode(String eduCode) {
        this.eduCode = eduCode;
    }

    @Column(name="emp_number", nullable=false)
    public int getEmpNumber() {
        return this.empNumber;
    }
    
    public void setEmpNumber(int empNumber) {
        this.empNumber = empNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpEducationId) ) return false;
		 EmpEducationId castOther = ( EmpEducationId ) other; 
         
		 return ( (this.getEduCode()==castOther.getEduCode()) || ( this.getEduCode()!=null && castOther.getEduCode()!=null && this.getEduCode().equals(castOther.getEduCode()) ) )
 && (this.getEmpNumber()==castOther.getEmpNumber());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEduCode() == null ? 0 : this.getEduCode().hashCode() );
         result = 37 * result + this.getEmpNumber();
         return result;
   }   


}


