package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpEmergencyContactsId generated by hbm2java
 */
@Embeddable
public class EmpEmergencyContactsId  implements java.io.Serializable {


     private int empNumber;
     private byte eecSeqno;

    public EmpEmergencyContactsId() {
    }

    public EmpEmergencyContactsId(int empNumber, byte eecSeqno) {
       this.empNumber = empNumber;
       this.eecSeqno = eecSeqno;
    }
   

    @Column(name="emp_number", nullable=false)
    public int getEmpNumber() {
        return this.empNumber;
    }
    
    public void setEmpNumber(int empNumber) {
        this.empNumber = empNumber;
    }

    @Column(name="eec_seqno", nullable=false, precision=2, scale=0)
    public byte getEecSeqno() {
        return this.eecSeqno;
    }
    
    public void setEecSeqno(byte eecSeqno) {
        this.eecSeqno = eecSeqno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpEmergencyContactsId) ) return false;
		 EmpEmergencyContactsId castOther = ( EmpEmergencyContactsId ) other; 
         
		 return (this.getEmpNumber()==castOther.getEmpNumber())
 && (this.getEecSeqno()==castOther.getEecSeqno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpNumber();
         result = 37 * result + this.getEecSeqno();
         return result;
   }   


}


