package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpEducation generated by hbm2java
 */
@Entity
@Table(name="emp_education"
    ,catalog="ashrm"
)
public class EmpEducation  implements java.io.Serializable {


     private EmpEducationId id;
     private Education education;
     private Employee employee;
     private String eduMajor;
     private Short eduYear;
     private String eduGpa;
     private Date eduStartDate;
     private Date eduEndDate;

    public EmpEducation() {
    }

	
    public EmpEducation(EmpEducationId id, Education education, Employee employee) {
        this.id = id;
        this.education = education;
        this.employee = employee;
    }
    public EmpEducation(EmpEducationId id, Education education, Employee employee, String eduMajor, Short eduYear, String eduGpa, Date eduStartDate, Date eduEndDate) {
       this.id = id;
       this.education = education;
       this.employee = employee;
       this.eduMajor = eduMajor;
       this.eduYear = eduYear;
       this.eduGpa = eduGpa;
       this.eduStartDate = eduStartDate;
       this.eduEndDate = eduEndDate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="eduCode", column=@Column(name="edu_code", nullable=false, length=13) ), 
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ) } )
    public EmpEducationId getId() {
        return this.id;
    }
    
    public void setId(EmpEducationId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="edu_code", nullable=false, insertable=false, updatable=false)
    public Education getEducation() {
        return this.education;
    }
    
    public void setEducation(Education education) {
        this.education = education;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    @Column(name="edu_major", length=100)
    public String getEduMajor() {
        return this.eduMajor;
    }
    
    public void setEduMajor(String eduMajor) {
        this.eduMajor = eduMajor;
    }
    
    @Column(name="edu_year", precision=4, scale=0)
    public Short getEduYear() {
        return this.eduYear;
    }
    
    public void setEduYear(Short eduYear) {
        this.eduYear = eduYear;
    }
    
    @Column(name="edu_gpa", length=25)
    public String getEduGpa() {
        return this.eduGpa;
    }
    
    public void setEduGpa(String eduGpa) {
        this.eduGpa = eduGpa;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="edu_start_date", length=19)
    public Date getEduStartDate() {
        return this.eduStartDate;
    }
    
    public void setEduStartDate(Date eduStartDate) {
        this.eduStartDate = eduStartDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="edu_end_date", length=19)
    public Date getEduEndDate() {
        return this.eduEndDate;
    }
    
    public void setEduEndDate(Date eduEndDate) {
        this.eduEndDate = eduEndDate;
    }




}


