package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpHistoryOfEalierPosId generated by hbm2java
 */
@Embeddable
public class EmpHistoryOfEalierPosId  implements java.io.Serializable {


     private int empNumber;
     private byte empSeqno;

    public EmpHistoryOfEalierPosId() {
    }

    public EmpHistoryOfEalierPosId(int empNumber, byte empSeqno) {
       this.empNumber = empNumber;
       this.empSeqno = empSeqno;
    }
   

    @Column(name="emp_number", nullable=false)
    public int getEmpNumber() {
        return this.empNumber;
    }
    
    public void setEmpNumber(int empNumber) {
        this.empNumber = empNumber;
    }

    @Column(name="emp_seqno", nullable=false, precision=2, scale=0)
    public byte getEmpSeqno() {
        return this.empSeqno;
    }
    
    public void setEmpSeqno(byte empSeqno) {
        this.empSeqno = empSeqno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpHistoryOfEalierPosId) ) return false;
		 EmpHistoryOfEalierPosId castOther = ( EmpHistoryOfEalierPosId ) other; 
         
		 return (this.getEmpNumber()==castOther.getEmpNumber())
 && (this.getEmpSeqno()==castOther.getEmpSeqno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpNumber();
         result = 37 * result + this.getEmpSeqno();
         return result;
   }   


}


