package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpHistoryOfEalierPos generated by hbm2java
 */
@Entity
@Table(name="emp_history_of_ealier_pos"
    ,catalog="ashrm"
)
public class EmpHistoryOfEalierPos  implements java.io.Serializable {


     private EmpHistoryOfEalierPosId id;
     private Employee employee;
     private String ehoepJobTitle;
     private String ehoepYears;

    public EmpHistoryOfEalierPos() {
    }

	
    public EmpHistoryOfEalierPos(EmpHistoryOfEalierPosId id, Employee employee) {
        this.id = id;
        this.employee = employee;
    }
    public EmpHistoryOfEalierPos(EmpHistoryOfEalierPosId id, Employee employee, String ehoepJobTitle, String ehoepYears) {
       this.id = id;
       this.employee = employee;
       this.ehoepJobTitle = ehoepJobTitle;
       this.ehoepYears = ehoepYears;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="empSeqno", column=@Column(name="emp_seqno", nullable=false, precision=2, scale=0) ) } )
    public EmpHistoryOfEalierPosId getId() {
        return this.id;
    }
    
    public void setId(EmpHistoryOfEalierPosId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    @Column(name="ehoep_job_title", length=100)
    public String getEhoepJobTitle() {
        return this.ehoepJobTitle;
    }
    
    public void setEhoepJobTitle(String ehoepJobTitle) {
        this.ehoepJobTitle = ehoepJobTitle;
    }
    
    @Column(name="ehoep_years", length=100)
    public String getEhoepYears() {
        return this.ehoepYears;
    }
    
    public void setEhoepYears(String ehoepYears) {
        this.ehoepYears = ehoepYears;
    }




}


