package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpLicenses generated by hbm2java
 */
@Entity
@Table(name="emp_licenses"
    ,catalog="ashrm"
)
public class EmpLicenses  implements java.io.Serializable {


     private EmpLicensesId id;
     private Licenses licenses;
     private Employee employee;
     private Date licensesDate;
     private Date licensesRenewalDate;

    public EmpLicenses() {
    }

	
    public EmpLicenses(EmpLicensesId id, Licenses licenses, Employee employee) {
        this.id = id;
        this.licenses = licenses;
        this.employee = employee;
    }
    public EmpLicenses(EmpLicensesId id, Licenses licenses, Employee employee, Date licensesDate, Date licensesRenewalDate) {
       this.id = id;
       this.licenses = licenses;
       this.employee = employee;
       this.licensesDate = licensesDate;
       this.licensesRenewalDate = licensesRenewalDate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="licensesCode", column=@Column(name="licenses_code", nullable=false, length=13) ) } )
    public EmpLicensesId getId() {
        return this.id;
    }
    
    public void setId(EmpLicensesId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="licenses_code", nullable=false, insertable=false, updatable=false)
    public Licenses getLicenses() {
        return this.licenses;
    }
    
    public void setLicenses(Licenses licenses) {
        this.licenses = licenses;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="licenses_date", length=10)
    public Date getLicensesDate() {
        return this.licensesDate;
    }
    
    public void setLicensesDate(Date licensesDate) {
        this.licensesDate = licensesDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="licenses_renewal_date", length=10)
    public Date getLicensesRenewalDate() {
        return this.licensesRenewalDate;
    }
    
    public void setLicensesRenewalDate(Date licensesRenewalDate) {
        this.licensesRenewalDate = licensesRenewalDate;
    }




}


