package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpLanguageId generated by hbm2java
 */
@Embeddable
public class EmpLanguageId  implements java.io.Serializable {


     private int empNumber;
     private String langCode;
     private short elangType;

    public EmpLanguageId() {
    }

    public EmpLanguageId(int empNumber, String langCode, short elangType) {
       this.empNumber = empNumber;
       this.langCode = langCode;
       this.elangType = elangType;
    }
   

    @Column(name="emp_number", nullable=false)
    public int getEmpNumber() {
        return this.empNumber;
    }
    
    public void setEmpNumber(int empNumber) {
        this.empNumber = empNumber;
    }

    @Column(name="lang_code", nullable=false, length=13)
    public String getLangCode() {
        return this.langCode;
    }
    
    public void setLangCode(String langCode) {
        this.langCode = langCode;
    }

    @Column(name="elang_type", nullable=false)
    public short getElangType() {
        return this.elangType;
    }
    
    public void setElangType(short elangType) {
        this.elangType = elangType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpLanguageId) ) return false;
		 EmpLanguageId castOther = ( EmpLanguageId ) other; 
         
		 return (this.getEmpNumber()==castOther.getEmpNumber())
 && ( (this.getLangCode()==castOther.getLangCode()) || ( this.getLangCode()!=null && castOther.getLangCode()!=null && this.getLangCode().equals(castOther.getLangCode()) ) )
 && (this.getElangType()==castOther.getElangType());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpNumber();
         result = 37 * result + ( getLangCode() == null ? 0 : this.getLangCode().hashCode() );
         result = 37 * result + this.getElangType();
         return result;
   }   


}


