package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpLanguage generated by hbm2java
 */
@Entity
@Table(name="emp_language"
    ,catalog="ashrm"
)
public class EmpLanguage  implements java.io.Serializable {


     private EmpLanguageId id;
     private Language language;
     private Employee employee;
     private Short competency;

    public EmpLanguage() {
    }

	
    public EmpLanguage(EmpLanguageId id, Language language, Employee employee) {
        this.id = id;
        this.language = language;
        this.employee = employee;
    }
    public EmpLanguage(EmpLanguageId id, Language language, Employee employee, Short competency) {
       this.id = id;
       this.language = language;
       this.employee = employee;
       this.competency = competency;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="langCode", column=@Column(name="lang_code", nullable=false, length=13) ), 
        @AttributeOverride(name="elangType", column=@Column(name="elang_type", nullable=false) ) } )
    public EmpLanguageId getId() {
        return this.id;
    }
    
    public void setId(EmpLanguageId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lang_code", nullable=false, insertable=false, updatable=false)
    public Language getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Language language) {
        this.language = language;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    @Column(name="competency")
    public Short getCompetency() {
        return this.competency;
    }
    
    public void setCompetency(Short competency) {
        this.competency = competency;
    }




}


