package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeeLeaveQuotaId generated by hbm2java
 */
@Embeddable
public class EmployeeLeaveQuotaId  implements java.io.Serializable {


     private String leaveTypeId;
     private int employeeId;
     private Date year;

    public EmployeeLeaveQuotaId() {
    }

    public EmployeeLeaveQuotaId(String leaveTypeId, int employeeId, Date year) {
       this.leaveTypeId = leaveTypeId;
       this.employeeId = employeeId;
       this.year = year;
    }
   

    @Column(name="leave_type_id", nullable=false, length=13)
    public String getLeaveTypeId() {
        return this.leaveTypeId;
    }
    
    public void setLeaveTypeId(String leaveTypeId) {
        this.leaveTypeId = leaveTypeId;
    }

    @Column(name="employee_id", nullable=false)
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    @Column(name="year", nullable=false, length=0)
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmployeeLeaveQuotaId) ) return false;
		 EmployeeLeaveQuotaId castOther = ( EmployeeLeaveQuotaId ) other; 
         
		 return ( (this.getLeaveTypeId()==castOther.getLeaveTypeId()) || ( this.getLeaveTypeId()!=null && castOther.getLeaveTypeId()!=null && this.getLeaveTypeId().equals(castOther.getLeaveTypeId()) ) )
 && (this.getEmployeeId()==castOther.getEmployeeId())
 && ( (this.getYear()==castOther.getYear()) || ( this.getYear()!=null && castOther.getYear()!=null && this.getYear().equals(castOther.getYear()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLeaveTypeId() == null ? 0 : this.getLeaveTypeId().hashCode() );
         result = 37 * result + this.getEmployeeId();
         result = 37 * result + ( getYear() == null ? 0 : this.getYear().hashCode() );
         return result;
   }   


}


