package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeLeaveQuota generated by hbm2java
 */
@Entity
@Table(name="employee_leave_quota"
    ,catalog="ashrm"
)
public class EmployeeLeaveQuota  implements java.io.Serializable {


     private EmployeeLeaveQuotaId id;
     private Employee employee;
     private Leavetype leavetype;
     private BigDecimal noOfDaysAllotted;
     private BigDecimal leaveTaken;
     private BigDecimal leaveBroughtForward;

    public EmployeeLeaveQuota() {
    }

	
    public EmployeeLeaveQuota(EmployeeLeaveQuotaId id, Employee employee, Leavetype leavetype) {
        this.id = id;
        this.employee = employee;
        this.leavetype = leavetype;
    }
    public EmployeeLeaveQuota(EmployeeLeaveQuotaId id, Employee employee, Leavetype leavetype, BigDecimal noOfDaysAllotted, BigDecimal leaveTaken, BigDecimal leaveBroughtForward) {
       this.id = id;
       this.employee = employee;
       this.leavetype = leavetype;
       this.noOfDaysAllotted = noOfDaysAllotted;
       this.leaveTaken = leaveTaken;
       this.leaveBroughtForward = leaveBroughtForward;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="leaveTypeId", column=@Column(name="leave_type_id", nullable=false, length=13) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="employee_id", nullable=false) ), 
        @AttributeOverride(name="year", column=@Column(name="year", nullable=false, length=0) ) } )
    public EmployeeLeaveQuotaId getId() {
        return this.id;
    }
    
    public void setId(EmployeeLeaveQuotaId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="leave_type_id", nullable=false, insertable=false, updatable=false)
    public Leavetype getLeavetype() {
        return this.leavetype;
    }
    
    public void setLeavetype(Leavetype leavetype) {
        this.leavetype = leavetype;
    }
    
    @Column(name="no_of_days_allotted", precision=6)
    public BigDecimal getNoOfDaysAllotted() {
        return this.noOfDaysAllotted;
    }
    
    public void setNoOfDaysAllotted(BigDecimal noOfDaysAllotted) {
        this.noOfDaysAllotted = noOfDaysAllotted;
    }
    
    @Column(name="leave_taken", precision=6)
    public BigDecimal getLeaveTaken() {
        return this.leaveTaken;
    }
    
    public void setLeaveTaken(BigDecimal leaveTaken) {
        this.leaveTaken = leaveTaken;
    }
    
    @Column(name="leave_brought_forward", precision=6)
    public BigDecimal getLeaveBroughtForward() {
        return this.leaveBroughtForward;
    }
    
    public void setLeaveBroughtForward(BigDecimal leaveBroughtForward) {
        this.leaveBroughtForward = leaveBroughtForward;
    }




}


