package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpMemberDetail generated by hbm2java
 */
@Entity
@Table(name="emp_member_detail"
    ,catalog="ashrm"
)
public class EmpMemberDetail  implements java.io.Serializable {


     private EmpMemberDetailId id;
     private MembershipType membershipType;
     private Employee employee;
     private Membership membership;
     private String emembSubscriptOwnership;
     private BigDecimal emembSubscriptAmount;
     private Date emembCommenceDate;
     private Date emembRenewalDate;

    public EmpMemberDetail() {
    }

	
    public EmpMemberDetail(EmpMemberDetailId id, MembershipType membershipType, Employee employee, Membership membership) {
        this.id = id;
        this.membershipType = membershipType;
        this.employee = employee;
        this.membership = membership;
    }
    public EmpMemberDetail(EmpMemberDetailId id, MembershipType membershipType, Employee employee, Membership membership, String emembSubscriptOwnership, BigDecimal emembSubscriptAmount, Date emembCommenceDate, Date emembRenewalDate) {
       this.id = id;
       this.membershipType = membershipType;
       this.employee = employee;
       this.membership = membership;
       this.emembSubscriptOwnership = emembSubscriptOwnership;
       this.emembSubscriptAmount = emembSubscriptAmount;
       this.emembCommenceDate = emembCommenceDate;
       this.emembRenewalDate = emembRenewalDate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="membshipCode", column=@Column(name="membship_code", nullable=false, length=13) ), 
        @AttributeOverride(name="membtypeCode", column=@Column(name="membtype_code", nullable=false, length=13) ) } )
    public EmpMemberDetailId getId() {
        return this.id;
    }
    
    public void setId(EmpMemberDetailId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="membtype_code", nullable=false, insertable=false, updatable=false)
    public MembershipType getMembershipType() {
        return this.membershipType;
    }
    
    public void setMembershipType(MembershipType membershipType) {
        this.membershipType = membershipType;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="membship_code", nullable=false, insertable=false, updatable=false)
    public Membership getMembership() {
        return this.membership;
    }
    
    public void setMembership(Membership membership) {
        this.membership = membership;
    }
    
    @Column(name="ememb_subscript_ownership", length=20)
    public String getEmembSubscriptOwnership() {
        return this.emembSubscriptOwnership;
    }
    
    public void setEmembSubscriptOwnership(String emembSubscriptOwnership) {
        this.emembSubscriptOwnership = emembSubscriptOwnership;
    }
    
    @Column(name="ememb_subscript_amount", precision=15)
    public BigDecimal getEmembSubscriptAmount() {
        return this.emembSubscriptAmount;
    }
    
    public void setEmembSubscriptAmount(BigDecimal emembSubscriptAmount) {
        this.emembSubscriptAmount = emembSubscriptAmount;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ememb_commence_date", length=19)
    public Date getEmembCommenceDate() {
        return this.emembCommenceDate;
    }
    
    public void setEmembCommenceDate(Date emembCommenceDate) {
        this.emembCommenceDate = emembCommenceDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ememb_renewal_date", length=19)
    public Date getEmembRenewalDate() {
        return this.emembRenewalDate;
    }
    
    public void setEmembRenewalDate(Date emembRenewalDate) {
        this.emembRenewalDate = emembRenewalDate;
    }




}


