package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpPassport generated by hbm2java
 */
@Entity
@Table(name="emp_passport"
    ,catalog="ashrm"
)
public class EmpPassport  implements java.io.Serializable {


     private EmpPassportId id;
     private Employee employee;
     private String epPassportNum;
     private Date epPassportissueddate;
     private Date epPassportexpiredate;
     private String epComments;
     private Short epPassportTypeFlg;
     private String epI9Status;
     private Date epI9ReviewDate;
     private String couCode;

    public EmpPassport() {
    }

	
    public EmpPassport(EmpPassportId id, Employee employee, String epPassportNum) {
        this.id = id;
        this.employee = employee;
        this.epPassportNum = epPassportNum;
    }
    public EmpPassport(EmpPassportId id, Employee employee, String epPassportNum, Date epPassportissueddate, Date epPassportexpiredate, String epComments, Short epPassportTypeFlg, String epI9Status, Date epI9ReviewDate, String couCode) {
       this.id = id;
       this.employee = employee;
       this.epPassportNum = epPassportNum;
       this.epPassportissueddate = epPassportissueddate;
       this.epPassportexpiredate = epPassportexpiredate;
       this.epComments = epComments;
       this.epPassportTypeFlg = epPassportTypeFlg;
       this.epI9Status = epI9Status;
       this.epI9ReviewDate = epI9ReviewDate;
       this.couCode = couCode;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="empNumber", column=@Column(name="emp_number", nullable=false) ), 
        @AttributeOverride(name="epSeqno", column=@Column(name="ep_seqno", nullable=false, precision=2, scale=0) ) } )
    public EmpPassportId getId() {
        return this.id;
    }
    
    public void setId(EmpPassportId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="emp_number", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    @Column(name="ep_passport_num", nullable=false, length=100)
    public String getEpPassportNum() {
        return this.epPassportNum;
    }
    
    public void setEpPassportNum(String epPassportNum) {
        this.epPassportNum = epPassportNum;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ep_passportissueddate", length=19)
    public Date getEpPassportissueddate() {
        return this.epPassportissueddate;
    }
    
    public void setEpPassportissueddate(Date epPassportissueddate) {
        this.epPassportissueddate = epPassportissueddate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ep_passportexpiredate", length=19)
    public Date getEpPassportexpiredate() {
        return this.epPassportexpiredate;
    }
    
    public void setEpPassportexpiredate(Date epPassportexpiredate) {
        this.epPassportexpiredate = epPassportexpiredate;
    }
    
    @Column(name="ep_comments")
    public String getEpComments() {
        return this.epComments;
    }
    
    public void setEpComments(String epComments) {
        this.epComments = epComments;
    }
    
    @Column(name="ep_passport_type_flg")
    public Short getEpPassportTypeFlg() {
        return this.epPassportTypeFlg;
    }
    
    public void setEpPassportTypeFlg(Short epPassportTypeFlg) {
        this.epPassportTypeFlg = epPassportTypeFlg;
    }
    
    @Column(name="ep_i9_status", length=100)
    public String getEpI9Status() {
        return this.epI9Status;
    }
    
    public void setEpI9Status(String epI9Status) {
        this.epI9Status = epI9Status;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="ep_i9_review_date", length=10)
    public Date getEpI9ReviewDate() {
        return this.epI9ReviewDate;
    }
    
    public void setEpI9ReviewDate(Date epI9ReviewDate) {
        this.epI9ReviewDate = epI9ReviewDate;
    }
    
    @Column(name="cou_code", length=6)
    public String getCouCode() {
        return this.couCode;
    }
    
    public void setCouCode(String couCode) {
        this.couCode = couCode;
    }




}


