package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Empreport generated by hbm2java
 */
@Entity
@Table(name="empreport"
    ,catalog="ashrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="rep_name") 
)
public class Empreport  implements java.io.Serializable {


     private String repCode;
     private String repName;
     private String repCridefStr;
     private String repFlddefStr;
     private Set<UserGroup> userGroups = new HashSet<UserGroup>(0);

    public Empreport() {
    }

	
    public Empreport(String repCode) {
        this.repCode = repCode;
    }
    public Empreport(String repCode, String repName, String repCridefStr, String repFlddefStr, Set<UserGroup> userGroups) {
       this.repCode = repCode;
       this.repName = repName;
       this.repCridefStr = repCridefStr;
       this.repFlddefStr = repFlddefStr;
       this.userGroups = userGroups;
    }
   
     @Id 
    
    @Column(name="rep_code", unique=true, nullable=false, length=13)
    public String getRepCode() {
        return this.repCode;
    }
    
    public void setRepCode(String repCode) {
        this.repCode = repCode;
    }
    
    @Column(name="rep_name", unique=true, length=60)
    public String getRepName() {
        return this.repName;
    }
    
    public void setRepName(String repName) {
        this.repName = repName;
    }
    
    @Column(name="rep_cridef_str", length=200)
    public String getRepCridefStr() {
        return this.repCridefStr;
    }
    
    public void setRepCridefStr(String repCridefStr) {
        this.repCridefStr = repCridefStr;
    }
    
    @Column(name="rep_flddef_str", length=200)
    public String getRepFlddefStr() {
        return this.repFlddefStr;
    }
    
    public void setRepFlddefStr(String repFlddefStr) {
        this.repFlddefStr = repFlddefStr;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="empreports")
    public Set<UserGroup> getUserGroups() {
        return this.userGroups;
    }
    
    public void setUserGroups(Set<UserGroup> userGroups) {
        this.userGroups = userGroups;
    }




}


