package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpReporttoId generated by hbm2java
 */
@Embeddable
public class EmpReporttoId  implements java.io.Serializable {


     private int erepSupEmpNumber;
     private int erepSubEmpNumber;
     private short erepReportingMode;

    public EmpReporttoId() {
    }

    public EmpReporttoId(int erepSupEmpNumber, int erepSubEmpNumber, short erepReportingMode) {
       this.erepSupEmpNumber = erepSupEmpNumber;
       this.erepSubEmpNumber = erepSubEmpNumber;
       this.erepReportingMode = erepReportingMode;
    }
   

    @Column(name="erep_sup_emp_number", nullable=false)
    public int getErepSupEmpNumber() {
        return this.erepSupEmpNumber;
    }
    
    public void setErepSupEmpNumber(int erepSupEmpNumber) {
        this.erepSupEmpNumber = erepSupEmpNumber;
    }

    @Column(name="erep_sub_emp_number", nullable=false)
    public int getErepSubEmpNumber() {
        return this.erepSubEmpNumber;
    }
    
    public void setErepSubEmpNumber(int erepSubEmpNumber) {
        this.erepSubEmpNumber = erepSubEmpNumber;
    }

    @Column(name="erep_reporting_mode", nullable=false)
    public short getErepReportingMode() {
        return this.erepReportingMode;
    }
    
    public void setErepReportingMode(short erepReportingMode) {
        this.erepReportingMode = erepReportingMode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpReporttoId) ) return false;
		 EmpReporttoId castOther = ( EmpReporttoId ) other; 
         
		 return (this.getErepSupEmpNumber()==castOther.getErepSupEmpNumber())
 && (this.getErepSubEmpNumber()==castOther.getErepSubEmpNumber())
 && (this.getErepReportingMode()==castOther.getErepReportingMode());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getErepSupEmpNumber();
         result = 37 * result + this.getErepSubEmpNumber();
         result = 37 * result + this.getErepReportingMode();
         return result;
   }   


}


