package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmpWorkExperienceId generated by hbm2java
 */
@Embeddable
public class EmpWorkExperienceId  implements java.io.Serializable {


     private int empNumber;
     private long eexpSeqno;

    public EmpWorkExperienceId() {
    }

    public EmpWorkExperienceId(int empNumber, long eexpSeqno) {
       this.empNumber = empNumber;
       this.eexpSeqno = eexpSeqno;
    }
   

    @Column(name="emp_number", nullable=false)
    public int getEmpNumber() {
        return this.empNumber;
    }
    
    public void setEmpNumber(int empNumber) {
        this.empNumber = empNumber;
    }

    @Column(name="eexp_seqno", nullable=false, precision=10, scale=0)
    public long getEexpSeqno() {
        return this.eexpSeqno;
    }
    
    public void setEexpSeqno(long eexpSeqno) {
        this.eexpSeqno = eexpSeqno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpWorkExperienceId) ) return false;
		 EmpWorkExperienceId castOther = ( EmpWorkExperienceId ) other; 
         
		 return (this.getEmpNumber()==castOther.getEmpNumber())
 && (this.getEexpSeqno()==castOther.getEexpSeqno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEmpNumber();
         result = 37 * result + (int) this.getEexpSeqno();
         return result;
   }   


}


