package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EthnicRace generated by hbm2java
 */
@Entity
@Table(name="ethnic_race"
    ,catalog="ashrm"
)
public class EthnicRace  implements java.io.Serializable {


     private String ethnicRaceCode;
     private String ethnicRaceDesc;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public EthnicRace() {
    }

	
    public EthnicRace(String ethnicRaceCode) {
        this.ethnicRaceCode = ethnicRaceCode;
    }
    public EthnicRace(String ethnicRaceCode, String ethnicRaceDesc, Set<Employee> employees) {
       this.ethnicRaceCode = ethnicRaceCode;
       this.ethnicRaceDesc = ethnicRaceDesc;
       this.employees = employees;
    }
   
     @Id 
    
    @Column(name="ethnic_race_code", unique=true, nullable=false, length=13)
    public String getEthnicRaceCode() {
        return this.ethnicRaceCode;
    }
    
    public void setEthnicRaceCode(String ethnicRaceCode) {
        this.ethnicRaceCode = ethnicRaceCode;
    }
    
    @Column(name="ethnic_race_desc", length=50)
    public String getEthnicRaceDesc() {
        return this.ethnicRaceDesc;
    }
    
    public void setEthnicRaceDesc(String ethnicRaceDesc) {
        this.ethnicRaceDesc = ethnicRaceDesc;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ethnicRace")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


