package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FileVersion generated by hbm2java
 */
@Entity
@Table(name="file_version"
    ,catalog="ashrm"
)
public class FileVersion  implements java.io.Serializable {


     private String id;
     private Users usersByModifiedBy;
     private Users usersByEnteredBy;
     private Module module;
     private String description;
     private Date enteredDate;
     private Date modifiedDate;
     private String name;
     private Set<Versions> versionses = new HashSet<Versions>(0);

    public FileVersion() {
    }

	
    public FileVersion(String id) {
        this.id = id;
    }
    public FileVersion(String id, Users usersByModifiedBy, Users usersByEnteredBy, Module module, String description, Date enteredDate, Date modifiedDate, String name, Set<Versions> versionses) {
       this.id = id;
       this.usersByModifiedBy = usersByModifiedBy;
       this.usersByEnteredBy = usersByEnteredBy;
       this.module = module;
       this.description = description;
       this.enteredDate = enteredDate;
       this.modifiedDate = modifiedDate;
       this.name = name;
       this.versionses = versionses;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modified_by")
    public Users getUsersByModifiedBy() {
        return this.usersByModifiedBy;
    }
    
    public void setUsersByModifiedBy(Users usersByModifiedBy) {
        this.usersByModifiedBy = usersByModifiedBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entered_by")
    public Users getUsersByEnteredBy() {
        return this.usersByEnteredBy;
    }
    
    public void setUsersByEnteredBy(Users usersByEnteredBy) {
        this.usersByEnteredBy = usersByEnteredBy;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="altered_module")
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }
    
    @Column(name="description", length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="entered_date", length=19)
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_date", length=19)
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="fileVersion")
    public Set<Versions> getVersionses() {
        return this.versionses;
    }
    
    public void setVersionses(Set<Versions> versionses) {
        this.versionses = versionses;
    }




}


