package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Geninfo generated by hbm2java
 */
@Entity
@Table(name="geninfo"
    ,catalog="ashrm"
)
public class Geninfo  implements java.io.Serializable {


     private String code;
     private String geninfoKeys;
     private String geninfoValues;

    public Geninfo() {
    }

	
    public Geninfo(String code) {
        this.code = code;
    }
    public Geninfo(String code, String geninfoKeys, String geninfoValues) {
       this.code = code;
       this.geninfoKeys = geninfoKeys;
       this.geninfoValues = geninfoValues;
    }
   
     @Id 
    
    @Column(name="code", unique=true, nullable=false, length=13)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="geninfo_keys", length=200)
    public String getGeninfoKeys() {
        return this.geninfoKeys;
    }
    
    public void setGeninfoKeys(String geninfoKeys) {
        this.geninfoKeys = geninfoKeys;
    }
    
    @Column(name="geninfo_values", length=800)
    public String getGeninfoValues() {
        return this.geninfoValues;
    }
    
    public void setGeninfoValues(String geninfoValues) {
        this.geninfoValues = geninfoValues;
    }




}


