package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hsp generated by hbm2java
 */
@Entity
@Table(name="hsp"
    ,catalog="ashrm"
)
public class Hsp  implements java.io.Serializable {


     private int id;
     private Employee employee;
     private Date benefitYear;
     private BigDecimal hspValue;
     private BigDecimal totalAcrued;
     private Date accruedLastUpdated;
     private BigDecimal amountPerDay;
     private Byte editedStatus;
     private Date terminationDate;
     private Byte halted;
     private Date haltedDate;
     private Byte terminated;

    public Hsp() {
    }

	
    public Hsp(int id, Employee employee, BigDecimal hspValue, BigDecimal totalAcrued, BigDecimal amountPerDay) {
        this.id = id;
        this.employee = employee;
        this.hspValue = hspValue;
        this.totalAcrued = totalAcrued;
        this.amountPerDay = amountPerDay;
    }
    public Hsp(int id, Employee employee, Date benefitYear, BigDecimal hspValue, BigDecimal totalAcrued, Date accruedLastUpdated, BigDecimal amountPerDay, Byte editedStatus, Date terminationDate, Byte halted, Date haltedDate, Byte terminated) {
       this.id = id;
       this.employee = employee;
       this.benefitYear = benefitYear;
       this.hspValue = hspValue;
       this.totalAcrued = totalAcrued;
       this.accruedLastUpdated = accruedLastUpdated;
       this.amountPerDay = amountPerDay;
       this.editedStatus = editedStatus;
       this.terminationDate = terminationDate;
       this.halted = halted;
       this.haltedDate = haltedDate;
       this.terminated = terminated;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="benefit_year", length=10)
    public Date getBenefitYear() {
        return this.benefitYear;
    }
    
    public void setBenefitYear(Date benefitYear) {
        this.benefitYear = benefitYear;
    }
    
    @Column(name="hsp_value", nullable=false, precision=10)
    public BigDecimal getHspValue() {
        return this.hspValue;
    }
    
    public void setHspValue(BigDecimal hspValue) {
        this.hspValue = hspValue;
    }
    
    @Column(name="total_acrued", nullable=false, precision=10)
    public BigDecimal getTotalAcrued() {
        return this.totalAcrued;
    }
    
    public void setTotalAcrued(BigDecimal totalAcrued) {
        this.totalAcrued = totalAcrued;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="accrued_last_updated", length=10)
    public Date getAccruedLastUpdated() {
        return this.accruedLastUpdated;
    }
    
    public void setAccruedLastUpdated(Date accruedLastUpdated) {
        this.accruedLastUpdated = accruedLastUpdated;
    }
    
    @Column(name="amount_per_day", nullable=false, precision=10)
    public BigDecimal getAmountPerDay() {
        return this.amountPerDay;
    }
    
    public void setAmountPerDay(BigDecimal amountPerDay) {
        this.amountPerDay = amountPerDay;
    }
    
    @Column(name="edited_status")
    public Byte getEditedStatus() {
        return this.editedStatus;
    }
    
    public void setEditedStatus(Byte editedStatus) {
        this.editedStatus = editedStatus;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="termination_date", length=10)
    public Date getTerminationDate() {
        return this.terminationDate;
    }
    
    public void setTerminationDate(Date terminationDate) {
        this.terminationDate = terminationDate;
    }
    
    @Column(name="halted")
    public Byte getHalted() {
        return this.halted;
    }
    
    public void setHalted(Byte halted) {
        this.halted = halted;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="halted_date", length=10)
    public Date getHaltedDate() {
        return this.haltedDate;
    }
    
    public void setHaltedDate(Date haltedDate) {
        this.haltedDate = haltedDate;
    }
    
    @Column(name="terminated")
    public Byte getTerminated() {
        return this.terminated;
    }
    
    public void setTerminated(Byte terminated) {
        this.terminated = terminated;
    }




}


