package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HspPaymentRequest generated by hbm2java
 */
@Entity
@Table(name="hsp_payment_request"
    ,catalog="ashrm"
)
public class HspPaymentRequest  implements java.io.Serializable {


     private int id;
     private Employee employee;
     private int hspId;
     private Date dateIncurred;
     private String providerName;
     private String personIncurringExpense;
     private String expenseDescription;
     private BigDecimal expenseAmount;
     private String paymentMadeTo;
     private String thirdPartyAccountNumber;
     private String mailAddress;
     private String comments;
     private Date datePaid;
     private String checkNumber;
     private Byte status;
     private String hrNotes;

    public HspPaymentRequest() {
    }

	
    public HspPaymentRequest(int id, Employee employee, int hspId, Date dateIncurred, BigDecimal expenseAmount) {
        this.id = id;
        this.employee = employee;
        this.hspId = hspId;
        this.dateIncurred = dateIncurred;
        this.expenseAmount = expenseAmount;
    }
    public HspPaymentRequest(int id, Employee employee, int hspId, Date dateIncurred, String providerName, String personIncurringExpense, String expenseDescription, BigDecimal expenseAmount, String paymentMadeTo, String thirdPartyAccountNumber, String mailAddress, String comments, Date datePaid, String checkNumber, Byte status, String hrNotes) {
       this.id = id;
       this.employee = employee;
       this.hspId = hspId;
       this.dateIncurred = dateIncurred;
       this.providerName = providerName;
       this.personIncurringExpense = personIncurringExpense;
       this.expenseDescription = expenseDescription;
       this.expenseAmount = expenseAmount;
       this.paymentMadeTo = paymentMadeTo;
       this.thirdPartyAccountNumber = thirdPartyAccountNumber;
       this.mailAddress = mailAddress;
       this.comments = comments;
       this.datePaid = datePaid;
       this.checkNumber = checkNumber;
       this.status = status;
       this.hrNotes = hrNotes;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    
    @Column(name="hsp_id", nullable=false)
    public int getHspId() {
        return this.hspId;
    }
    
    public void setHspId(int hspId) {
        this.hspId = hspId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_incurred", nullable=false, length=10)
    public Date getDateIncurred() {
        return this.dateIncurred;
    }
    
    public void setDateIncurred(Date dateIncurred) {
        this.dateIncurred = dateIncurred;
    }
    
    @Column(name="provider_name", length=100)
    public String getProviderName() {
        return this.providerName;
    }
    
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }
    
    @Column(name="person_incurring_expense", length=100)
    public String getPersonIncurringExpense() {
        return this.personIncurringExpense;
    }
    
    public void setPersonIncurringExpense(String personIncurringExpense) {
        this.personIncurringExpense = personIncurringExpense;
    }
    
    @Column(name="expense_description", length=250)
    public String getExpenseDescription() {
        return this.expenseDescription;
    }
    
    public void setExpenseDescription(String expenseDescription) {
        this.expenseDescription = expenseDescription;
    }
    
    @Column(name="expense_amount", nullable=false, precision=10)
    public BigDecimal getExpenseAmount() {
        return this.expenseAmount;
    }
    
    public void setExpenseAmount(BigDecimal expenseAmount) {
        this.expenseAmount = expenseAmount;
    }
    
    @Column(name="payment_made_to", length=100)
    public String getPaymentMadeTo() {
        return this.paymentMadeTo;
    }
    
    public void setPaymentMadeTo(String paymentMadeTo) {
        this.paymentMadeTo = paymentMadeTo;
    }
    
    @Column(name="third_party_account_number", length=50)
    public String getThirdPartyAccountNumber() {
        return this.thirdPartyAccountNumber;
    }
    
    public void setThirdPartyAccountNumber(String thirdPartyAccountNumber) {
        this.thirdPartyAccountNumber = thirdPartyAccountNumber;
    }
    
    @Column(name="mail_address", length=250)
    public String getMailAddress() {
        return this.mailAddress;
    }
    
    public void setMailAddress(String mailAddress) {
        this.mailAddress = mailAddress;
    }
    
    @Column(name="comments", length=250)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_paid", length=10)
    public Date getDatePaid() {
        return this.datePaid;
    }
    
    public void setDatePaid(Date datePaid) {
        this.datePaid = datePaid;
    }
    
    @Column(name="check_number", length=50)
    public String getCheckNumber() {
        return this.checkNumber;
    }
    
    public void setCheckNumber(String checkNumber) {
        this.checkNumber = checkNumber;
    }
    
    @Column(name="status")
    public Byte getStatus() {
        return this.status;
    }
    
    public void setStatus(Byte status) {
        this.status = status;
    }
    
    @Column(name="hr_notes", length=250)
    public String getHrNotes() {
        return this.hrNotes;
    }
    
    public void setHrNotes(String hrNotes) {
        this.hrNotes = hrNotes;
    }




}


