package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HspSummary generated by hbm2java
 */
@Entity
@Table(name="hsp_summary"
    ,catalog="ashrm"
)
public class HspSummary  implements java.io.Serializable {


     private int summaryId;
     private int employeeId;
     private byte hspPlanId;
     private int hspPlanYear;
     private byte hspPlanStatus;
     private BigDecimal annualLimit;
     private BigDecimal employerAmount;
     private BigDecimal employeeAmount;
     private BigDecimal totalAccrued;
     private BigDecimal totalUsed;

    public HspSummary() {
    }

    public HspSummary(int summaryId, int employeeId, byte hspPlanId, int hspPlanYear, byte hspPlanStatus, BigDecimal annualLimit, BigDecimal employerAmount, BigDecimal employeeAmount, BigDecimal totalAccrued, BigDecimal totalUsed) {
       this.summaryId = summaryId;
       this.employeeId = employeeId;
       this.hspPlanId = hspPlanId;
       this.hspPlanYear = hspPlanYear;
       this.hspPlanStatus = hspPlanStatus;
       this.annualLimit = annualLimit;
       this.employerAmount = employerAmount;
       this.employeeAmount = employeeAmount;
       this.totalAccrued = totalAccrued;
       this.totalUsed = totalUsed;
    }
   
     @Id 
    
    @Column(name="summary_id", unique=true, nullable=false)
    public int getSummaryId() {
        return this.summaryId;
    }
    
    public void setSummaryId(int summaryId) {
        this.summaryId = summaryId;
    }
    
    @Column(name="employee_id", nullable=false)
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="hsp_plan_id", nullable=false)
    public byte getHspPlanId() {
        return this.hspPlanId;
    }
    
    public void setHspPlanId(byte hspPlanId) {
        this.hspPlanId = hspPlanId;
    }
    
    @Column(name="hsp_plan_year", nullable=false)
    public int getHspPlanYear() {
        return this.hspPlanYear;
    }
    
    public void setHspPlanYear(int hspPlanYear) {
        this.hspPlanYear = hspPlanYear;
    }
    
    @Column(name="hsp_plan_status", nullable=false)
    public byte getHspPlanStatus() {
        return this.hspPlanStatus;
    }
    
    public void setHspPlanStatus(byte hspPlanStatus) {
        this.hspPlanStatus = hspPlanStatus;
    }
    
    @Column(name="annual_limit", nullable=false, precision=10)
    public BigDecimal getAnnualLimit() {
        return this.annualLimit;
    }
    
    public void setAnnualLimit(BigDecimal annualLimit) {
        this.annualLimit = annualLimit;
    }
    
    @Column(name="employer_amount", nullable=false, precision=10)
    public BigDecimal getEmployerAmount() {
        return this.employerAmount;
    }
    
    public void setEmployerAmount(BigDecimal employerAmount) {
        this.employerAmount = employerAmount;
    }
    
    @Column(name="employee_amount", nullable=false, precision=10)
    public BigDecimal getEmployeeAmount() {
        return this.employeeAmount;
    }
    
    public void setEmployeeAmount(BigDecimal employeeAmount) {
        this.employeeAmount = employeeAmount;
    }
    
    @Column(name="total_accrued", nullable=false, precision=10)
    public BigDecimal getTotalAccrued() {
        return this.totalAccrued;
    }
    
    public void setTotalAccrued(BigDecimal totalAccrued) {
        this.totalAccrued = totalAccrued;
    }
    
    @Column(name="total_used", nullable=false, precision=10)
    public BigDecimal getTotalUsed() {
        return this.totalUsed;
    }
    
    public void setTotalUsed(BigDecimal totalUsed) {
        this.totalUsed = totalUsed;
    }




}


