package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobApplicationEvents generated by hbm2java
 */
@Entity
@Table(name="job_application_events"
    ,catalog="ashrm"
)
public class JobApplicationEvents  implements java.io.Serializable {


     private int id;
     private Users users;
     private JobApplication jobApplication;
     private Employee employee;
     private Date createdTime;
     private Date eventTime;
     private Short eventType;
     private Short status;
     private String notes;

    public JobApplicationEvents() {
    }

	
    public JobApplicationEvents(int id, JobApplication jobApplication) {
        this.id = id;
        this.jobApplication = jobApplication;
    }
    public JobApplicationEvents(int id, Users users, JobApplication jobApplication, Employee employee, Date createdTime, Date eventTime, Short eventType, Short status, String notes) {
       this.id = id;
       this.users = users;
       this.jobApplication = jobApplication;
       this.employee = employee;
       this.createdTime = createdTime;
       this.eventTime = eventTime;
       this.eventType = eventType;
       this.status = status;
       this.notes = notes;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="created_by")
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="application_id", nullable=false)
    public JobApplication getJobApplication() {
        return this.jobApplication;
    }
    
    public void setJobApplication(JobApplication jobApplication) {
        this.jobApplication = jobApplication;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="owner")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time", length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="event_time", length=19)
    public Date getEventTime() {
        return this.eventTime;
    }
    
    public void setEventTime(Date eventTime) {
        this.eventTime = eventTime;
    }
    
    @Column(name="event_type")
    public Short getEventType() {
        return this.eventType;
    }
    
    public void setEventType(Short eventType) {
        this.eventType = eventType;
    }
    
    @Column(name="status")
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }
    
    @Column(name="notes", length=65535)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


