package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JobSpec generated by hbm2java
 */
@Entity
@Table(name="job_spec"
    ,catalog="ashrm"
)
public class JobSpec  implements java.io.Serializable {


     private int jobspecId;
     private String jobspecName;
     private String jobspecDesc;
     private String jobspecDuties;
     private Set<JobTitle> jobTitles = new HashSet<JobTitle>(0);

    public JobSpec() {
    }

	
    public JobSpec(int jobspecId) {
        this.jobspecId = jobspecId;
    }
    public JobSpec(int jobspecId, String jobspecName, String jobspecDesc, String jobspecDuties, Set<JobTitle> jobTitles) {
       this.jobspecId = jobspecId;
       this.jobspecName = jobspecName;
       this.jobspecDesc = jobspecDesc;
       this.jobspecDuties = jobspecDuties;
       this.jobTitles = jobTitles;
    }
   
     @Id 
    
    @Column(name="jobspec_id", unique=true, nullable=false)
    public int getJobspecId() {
        return this.jobspecId;
    }
    
    public void setJobspecId(int jobspecId) {
        this.jobspecId = jobspecId;
    }
    
    @Column(name="jobspec_name", length=50)
    public String getJobspecName() {
        return this.jobspecName;
    }
    
    public void setJobspecName(String jobspecName) {
        this.jobspecName = jobspecName;
    }
    
    @Column(name="jobspec_desc", length=65535)
    public String getJobspecDesc() {
        return this.jobspecDesc;
    }
    
    public void setJobspecDesc(String jobspecDesc) {
        this.jobspecDesc = jobspecDesc;
    }
    
    @Column(name="jobspec_duties", length=65535)
    public String getJobspecDuties() {
        return this.jobspecDuties;
    }
    
    public void setJobspecDuties(String jobspecDuties) {
        this.jobspecDuties = jobspecDuties;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="jobSpec")
    public Set<JobTitle> getJobTitles() {
        return this.jobTitles;
    }
    
    public void setJobTitles(Set<JobTitle> jobTitles) {
        this.jobTitles = jobTitles;
    }




}


