package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JobVacancy generated by hbm2java
 */
@Entity
@Table(name="job_vacancy"
    ,catalog="ashrm"
)
public class JobVacancy  implements java.io.Serializable {


     private int vacancyId;
     private Employee employee;
     private JobTitle jobTitle;
     private boolean active;
     private String description;
     private Set<JobApplication> jobApplications = new HashSet<JobApplication>(0);

    public JobVacancy() {
    }

	
    public JobVacancy(int vacancyId, boolean active) {
        this.vacancyId = vacancyId;
        this.active = active;
    }
    public JobVacancy(int vacancyId, Employee employee, JobTitle jobTitle, boolean active, String description, Set<JobApplication> jobApplications) {
       this.vacancyId = vacancyId;
       this.employee = employee;
       this.jobTitle = jobTitle;
       this.active = active;
       this.description = description;
       this.jobApplications = jobApplications;
    }
   
     @Id 
    
    @Column(name="vacancy_id", unique=true, nullable=false)
    public int getVacancyId() {
        return this.vacancyId;
    }
    
    public void setVacancyId(int vacancyId) {
        this.vacancyId = vacancyId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="manager_id")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jobtit_code")
    public JobTitle getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(JobTitle jobTitle) {
        this.jobTitle = jobTitle;
    }
    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="jobVacancy")
    public Set<JobApplication> getJobApplications() {
        return this.jobApplications;
    }
    
    public void setJobApplications(Set<JobApplication> jobApplications) {
        this.jobApplications = jobApplications;
    }




}


