package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Kpi generated by hbm2java
 */
@Entity
@Table(name="kpi"
    ,catalog="ashrm"
)
public class Kpi  implements java.io.Serializable {


     private int id;
     private String jobTitleCode;
     private String description;
     private Double rateMin;
     private Double rateMax;
     private Byte rateDefault;
     private Byte isActive;

    public Kpi() {
    }

	
    public Kpi(int id) {
        this.id = id;
    }
    public Kpi(int id, String jobTitleCode, String description, Double rateMin, Double rateMax, Byte rateDefault, Byte isActive) {
       this.id = id;
       this.jobTitleCode = jobTitleCode;
       this.description = description;
       this.rateMin = rateMin;
       this.rateMax = rateMax;
       this.rateDefault = rateDefault;
       this.isActive = isActive;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="job_title_code", length=13)
    public String getJobTitleCode() {
        return this.jobTitleCode;
    }
    
    public void setJobTitleCode(String jobTitleCode) {
        this.jobTitleCode = jobTitleCode;
    }
    
    @Column(name="description", length=200)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="rate_min", precision=22, scale=0)
    public Double getRateMin() {
        return this.rateMin;
    }
    
    public void setRateMin(Double rateMin) {
        this.rateMin = rateMin;
    }
    
    @Column(name="rate_max", precision=22, scale=0)
    public Double getRateMax() {
        return this.rateMax;
    }
    
    public void setRateMax(Double rateMax) {
        this.rateMax = rateMax;
    }
    
    @Column(name="rate_default")
    public Byte getRateDefault() {
        return this.rateDefault;
    }
    
    public void setRateDefault(Byte rateDefault) {
        this.rateDefault = rateDefault;
    }
    
    @Column(name="is_active")
    public Byte getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }




}


