package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name="language"
    ,catalog="ashrm"
)
public class Language  implements java.io.Serializable {


     private String langCode;
     private String langName;
     private Set<EmpLanguage> empLanguages = new HashSet<EmpLanguage>(0);

    public Language() {
    }

	
    public Language(String langCode) {
        this.langCode = langCode;
    }
    public Language(String langCode, String langName, Set<EmpLanguage> empLanguages) {
       this.langCode = langCode;
       this.langName = langName;
       this.empLanguages = empLanguages;
    }
   
     @Id 
    
    @Column(name="lang_code", unique=true, nullable=false, length=13)
    public String getLangCode() {
        return this.langCode;
    }
    
    public void setLangCode(String langCode) {
        this.langCode = langCode;
    }
    
    @Column(name="lang_name", length=120)
    public String getLangName() {
        return this.langName;
    }
    
    public void setLangName(String langName) {
        this.langName = langName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="language")
    public Set<EmpLanguage> getEmpLanguages() {
        return this.empLanguages;
    }
    
    public void setEmpLanguages(Set<EmpLanguage> empLanguages) {
        this.empLanguages = empLanguages;
    }




}


