package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LeaveRequests generated by hbm2java
 */
@Entity
@Table(name="leave_requests"
    ,catalog="ashrm"
)
public class LeaveRequests  implements java.io.Serializable {


     private LeaveRequestsId id;
     private Employee employee;
     private Leavetype leavetype;
     private String leaveTypeName;
     private Date dateApplied;
     private Set<Leave> leaves = new HashSet<Leave>(0);

    public LeaveRequests() {
    }

	
    public LeaveRequests(LeaveRequestsId id, Employee employee, Leavetype leavetype, Date dateApplied) {
        this.id = id;
        this.employee = employee;
        this.leavetype = leavetype;
        this.dateApplied = dateApplied;
    }
    public LeaveRequests(LeaveRequestsId id, Employee employee, Leavetype leavetype, String leaveTypeName, Date dateApplied, Set<Leave> leaves) {
       this.id = id;
       this.employee = employee;
       this.leavetype = leavetype;
       this.leaveTypeName = leaveTypeName;
       this.dateApplied = dateApplied;
       this.leaves = leaves;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="leaveRequestId", column=@Column(name="leave_request_id", nullable=false) ), 
        @AttributeOverride(name="leaveTypeId", column=@Column(name="leave_type_id", nullable=false, length=13) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="employee_id", nullable=false) ) } )
    public LeaveRequestsId getId() {
        return this.id;
    }
    
    public void setId(LeaveRequestsId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="leave_type_id", nullable=false, insertable=false, updatable=false)
    public Leavetype getLeavetype() {
        return this.leavetype;
    }
    
    public void setLeavetype(Leavetype leavetype) {
        this.leavetype = leavetype;
    }
    
    @Column(name="leave_type_name", length=20)
    public String getLeaveTypeName() {
        return this.leaveTypeName;
    }
    
    public void setLeaveTypeName(String leaveTypeName) {
        this.leaveTypeName = leaveTypeName;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="date_applied", nullable=false, length=10)
    public Date getDateApplied() {
        return this.dateApplied;
    }
    
    public void setDateApplied(Date dateApplied) {
        this.dateApplied = dateApplied;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="leaveRequests")
    public Set<Leave> getLeaves() {
        return this.leaves;
    }
    
    public void setLeaves(Set<Leave> leaves) {
        this.leaves = leaves;
    }




}


