package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Leave generated by hbm2java
 */
@Entity
@Table(name="leave"
    ,catalog="ashrm"
)
public class Leave  implements java.io.Serializable {


     private LeaveId id;
     private LeaveRequests leaveRequests;
     private Date leaveDate;
     private BigDecimal leaveLengthHours;
     private BigDecimal leaveLengthDays;
     private Short leaveStatus;
     private String leaveComments;
     private Date startTime;
     private Date endTime;

    public Leave() {
    }

	
    public Leave(LeaveId id, LeaveRequests leaveRequests) {
        this.id = id;
        this.leaveRequests = leaveRequests;
    }
    public Leave(LeaveId id, LeaveRequests leaveRequests, Date leaveDate, BigDecimal leaveLengthHours, BigDecimal leaveLengthDays, Short leaveStatus, String leaveComments, Date startTime, Date endTime) {
       this.id = id;
       this.leaveRequests = leaveRequests;
       this.leaveDate = leaveDate;
       this.leaveLengthHours = leaveLengthHours;
       this.leaveLengthDays = leaveLengthDays;
       this.leaveStatus = leaveStatus;
       this.leaveComments = leaveComments;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="leaveId", column=@Column(name="leave_id", nullable=false) ), 
        @AttributeOverride(name="leaveRequestId", column=@Column(name="leave_request_id", nullable=false) ), 
        @AttributeOverride(name="leaveTypeId", column=@Column(name="leave_type_id", nullable=false, length=13) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="employee_id", nullable=false) ) } )
    public LeaveId getId() {
        return this.id;
    }
    
    public void setId(LeaveId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="leave_request_id", referencedColumnName="leave_request_id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="leave_type_id", referencedColumnName="leave_type_id", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="employee_id", referencedColumnName="employee_id", nullable=false, insertable=false, updatable=false) } )
    public LeaveRequests getLeaveRequests() {
        return this.leaveRequests;
    }
    
    public void setLeaveRequests(LeaveRequests leaveRequests) {
        this.leaveRequests = leaveRequests;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="leave_date", length=10)
    public Date getLeaveDate() {
        return this.leaveDate;
    }
    
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }
    
    @Column(name="leave_length_hours", precision=6)
    public BigDecimal getLeaveLengthHours() {
        return this.leaveLengthHours;
    }
    
    public void setLeaveLengthHours(BigDecimal leaveLengthHours) {
        this.leaveLengthHours = leaveLengthHours;
    }
    
    @Column(name="leave_length_days", precision=4)
    public BigDecimal getLeaveLengthDays() {
        return this.leaveLengthDays;
    }
    
    public void setLeaveLengthDays(BigDecimal leaveLengthDays) {
        this.leaveLengthDays = leaveLengthDays;
    }
    
    @Column(name="leave_status")
    public Short getLeaveStatus() {
        return this.leaveStatus;
    }
    
    public void setLeaveStatus(Short leaveStatus) {
        this.leaveStatus = leaveStatus;
    }
    
    @Column(name="leave_comments", length=256)
    public String getLeaveComments() {
        return this.leaveComments;
    }
    
    public void setLeaveComments(String leaveComments) {
        this.leaveComments = leaveComments;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="start_time", length=8)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    @Temporal(TemporalType.TIME)
    @Column(name="end_time", length=8)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }




}


