package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LeaveId generated by hbm2java
 */
@Embeddable
public class LeaveId  implements java.io.Serializable {


     private int leaveId;
     private int leaveRequestId;
     private String leaveTypeId;
     private int employeeId;

    public LeaveId() {
    }

    public LeaveId(int leaveId, int leaveRequestId, String leaveTypeId, int employeeId) {
       this.leaveId = leaveId;
       this.leaveRequestId = leaveRequestId;
       this.leaveTypeId = leaveTypeId;
       this.employeeId = employeeId;
    }
   

    @Column(name="leave_id", nullable=false)
    public int getLeaveId() {
        return this.leaveId;
    }
    
    public void setLeaveId(int leaveId) {
        this.leaveId = leaveId;
    }

    @Column(name="leave_request_id", nullable=false)
    public int getLeaveRequestId() {
        return this.leaveRequestId;
    }
    
    public void setLeaveRequestId(int leaveRequestId) {
        this.leaveRequestId = leaveRequestId;
    }

    @Column(name="leave_type_id", nullable=false, length=13)
    public String getLeaveTypeId() {
        return this.leaveTypeId;
    }
    
    public void setLeaveTypeId(String leaveTypeId) {
        this.leaveTypeId = leaveTypeId;
    }

    @Column(name="employee_id", nullable=false)
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LeaveId) ) return false;
		 LeaveId castOther = ( LeaveId ) other; 
         
		 return (this.getLeaveId()==castOther.getLeaveId())
 && (this.getLeaveRequestId()==castOther.getLeaveRequestId())
 && ( (this.getLeaveTypeId()==castOther.getLeaveTypeId()) || ( this.getLeaveTypeId()!=null && castOther.getLeaveTypeId()!=null && this.getLeaveTypeId().equals(castOther.getLeaveTypeId()) ) )
 && (this.getEmployeeId()==castOther.getEmployeeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLeaveId();
         result = 37 * result + this.getLeaveRequestId();
         result = 37 * result + ( getLeaveTypeId() == null ? 0 : this.getLeaveTypeId().hashCode() );
         result = 37 * result + this.getEmployeeId();
         return result;
   }   


}


