package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="location"
    ,catalog="ashrm"
)
public class Location  implements java.io.Serializable {


     private String locCode;
     private Country country;
     private String locName;
     private String locState;
     private String locCity;
     private String locAdd;
     private String locZip;
     private String locPhone;
     private String locFax;
     private String locComments;
     private Set<Employee> employees = new HashSet<Employee>(0);
     private Set<Compstructtree> compstructtrees = new HashSet<Compstructtree>(0);

    public Location() {
    }

	
    public Location(String locCode) {
        this.locCode = locCode;
    }
    public Location(String locCode, Country country, String locName, String locState, String locCity, String locAdd, String locZip, String locPhone, String locFax, String locComments, Set<Employee> employees, Set<Compstructtree> compstructtrees) {
       this.locCode = locCode;
       this.country = country;
       this.locName = locName;
       this.locState = locState;
       this.locCity = locCity;
       this.locAdd = locAdd;
       this.locZip = locZip;
       this.locPhone = locPhone;
       this.locFax = locFax;
       this.locComments = locComments;
       this.employees = employees;
       this.compstructtrees = compstructtrees;
    }
   
     @Id 
    
    @Column(name="loc_code", unique=true, nullable=false, length=13)
    public String getLocCode() {
        return this.locCode;
    }
    
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loc_country")
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }
    
    @Column(name="loc_name", length=100)
    public String getLocName() {
        return this.locName;
    }
    
    public void setLocName(String locName) {
        this.locName = locName;
    }
    
    @Column(name="loc_state", length=50)
    public String getLocState() {
        return this.locState;
    }
    
    public void setLocState(String locState) {
        this.locState = locState;
    }
    
    @Column(name="loc_city", length=50)
    public String getLocCity() {
        return this.locCity;
    }
    
    public void setLocCity(String locCity) {
        this.locCity = locCity;
    }
    
    @Column(name="loc_add", length=100)
    public String getLocAdd() {
        return this.locAdd;
    }
    
    public void setLocAdd(String locAdd) {
        this.locAdd = locAdd;
    }
    
    @Column(name="loc_zip", length=10)
    public String getLocZip() {
        return this.locZip;
    }
    
    public void setLocZip(String locZip) {
        this.locZip = locZip;
    }
    
    @Column(name="loc_phone", length=30)
    public String getLocPhone() {
        return this.locPhone;
    }
    
    public void setLocPhone(String locPhone) {
        this.locPhone = locPhone;
    }
    
    @Column(name="loc_fax", length=30)
    public String getLocFax() {
        return this.locFax;
    }
    
    public void setLocFax(String locFax) {
        this.locFax = locFax;
    }
    
    @Column(name="loc_comments", length=100)
    public String getLocComments() {
        return this.locComments;
    }
    
    public void setLocComments(String locComments) {
        this.locComments = locComments;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="locations")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="location")
    public Set<Compstructtree> getCompstructtrees() {
        return this.compstructtrees;
    }
    
    public void setCompstructtrees(Set<Compstructtree> compstructtrees) {
        this.compstructtrees = compstructtrees;
    }




}


