package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Membership generated by hbm2java
 */
@Entity
@Table(name="membership"
    ,catalog="ashrm"
)
public class Membership  implements java.io.Serializable {


     private String membshipCode;
     private MembershipType membershipType;
     private String membshipName;
     private Set<EmpMemberDetail> empMemberDetails = new HashSet<EmpMemberDetail>(0);

    public Membership() {
    }

	
    public Membership(String membshipCode) {
        this.membshipCode = membshipCode;
    }
    public Membership(String membshipCode, MembershipType membershipType, String membshipName, Set<EmpMemberDetail> empMemberDetails) {
       this.membshipCode = membshipCode;
       this.membershipType = membershipType;
       this.membshipName = membshipName;
       this.empMemberDetails = empMemberDetails;
    }
   
     @Id 
    
    @Column(name="membship_code", unique=true, nullable=false, length=13)
    public String getMembshipCode() {
        return this.membshipCode;
    }
    
    public void setMembshipCode(String membshipCode) {
        this.membshipCode = membshipCode;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="membtype_code")
    public MembershipType getMembershipType() {
        return this.membershipType;
    }
    
    public void setMembershipType(MembershipType membershipType) {
        this.membershipType = membershipType;
    }
    
    @Column(name="membship_name", length=120)
    public String getMembshipName() {
        return this.membshipName;
    }
    
    public void setMembshipName(String membshipName) {
        this.membshipName = membshipName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="membership")
    public Set<EmpMemberDetail> getEmpMemberDetails() {
        return this.empMemberDetails;
    }
    
    public void setEmpMemberDetails(Set<EmpMemberDetail> empMemberDetails) {
        this.empMemberDetails = empMemberDetails;
    }




}


