package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nationality generated by hbm2java
 */
@Entity
@Table(name="nationality"
    ,catalog="ashrm"
)
public class Nationality  implements java.io.Serializable {


     private String natCode;
     private String natName;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Nationality() {
    }

	
    public Nationality(String natCode) {
        this.natCode = natCode;
    }
    public Nationality(String natCode, String natName, Set<Employee> employees) {
       this.natCode = natCode;
       this.natName = natName;
       this.employees = employees;
    }
   
     @Id 
    
    @Column(name="nat_code", unique=true, nullable=false, length=13)
    public String getNatCode() {
        return this.natCode;
    }
    
    public void setNatCode(String natCode) {
        this.natCode = natCode;
    }
    
    @Column(name="nat_name", length=120)
    public String getNatName() {
        return this.natName;
    }
    
    public void setNatName(String natName) {
        this.natName = natName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="nationality")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


