package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerformanceReviewComments generated by hbm2java
 */
@Entity
@Table(name="performance_review_comments"
    ,catalog="ashrm"
)
public class PerformanceReviewComments  implements java.io.Serializable {


     private Integer id;
     private int prId;
     private Integer employeeId;
     private String comment;
     private Date createDate;

    public PerformanceReviewComments() {
    }

	
    public PerformanceReviewComments(int prId, Date createDate) {
        this.prId = prId;
        this.createDate = createDate;
    }
    public PerformanceReviewComments(int prId, Integer employeeId, String comment, Date createDate) {
       this.prId = prId;
       this.employeeId = employeeId;
       this.comment = comment;
       this.createDate = createDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="pr_id", nullable=false)
    public int getPrId() {
        return this.prId;
    }
    
    public void setPrId(int prId) {
        this.prId = prId;
    }
    
    @Column(name="employee_id")
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="comment", length=65535)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="create_date", nullable=false, length=10)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


