package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerformanceReview generated by hbm2java
 */
@Entity
@Table(name="performance_review"
    ,catalog="ashrm"
)
public class PerformanceReview  implements java.io.Serializable {


     private int id;
     private int employeeId;
     private int reviewerId;
     private String creatorId;
     private String jobTitleCode;
     private Integer subDivisionId;
     private Date creationDate;
     private Date periodFrom;
     private Date periodTo;
     private Date dueDate;
     private Byte state;
     private String kpis;

    public PerformanceReview() {
    }

	
    public PerformanceReview(int id, int employeeId, int reviewerId, String jobTitleCode, Date creationDate, Date periodFrom, Date periodTo, Date dueDate) {
        this.id = id;
        this.employeeId = employeeId;
        this.reviewerId = reviewerId;
        this.jobTitleCode = jobTitleCode;
        this.creationDate = creationDate;
        this.periodFrom = periodFrom;
        this.periodTo = periodTo;
        this.dueDate = dueDate;
    }
    public PerformanceReview(int id, int employeeId, int reviewerId, String creatorId, String jobTitleCode, Integer subDivisionId, Date creationDate, Date periodFrom, Date periodTo, Date dueDate, Byte state, String kpis) {
       this.id = id;
       this.employeeId = employeeId;
       this.reviewerId = reviewerId;
       this.creatorId = creatorId;
       this.jobTitleCode = jobTitleCode;
       this.subDivisionId = subDivisionId;
       this.creationDate = creationDate;
       this.periodFrom = periodFrom;
       this.periodTo = periodTo;
       this.dueDate = dueDate;
       this.state = state;
       this.kpis = kpis;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="employee_id", nullable=false)
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }
    
    @Column(name="reviewer_id", nullable=false)
    public int getReviewerId() {
        return this.reviewerId;
    }
    
    public void setReviewerId(int reviewerId) {
        this.reviewerId = reviewerId;
    }
    
    @Column(name="creator_id", length=36)
    public String getCreatorId() {
        return this.creatorId;
    }
    
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }
    
    @Column(name="job_title_code", nullable=false, length=10)
    public String getJobTitleCode() {
        return this.jobTitleCode;
    }
    
    public void setJobTitleCode(String jobTitleCode) {
        this.jobTitleCode = jobTitleCode;
    }
    
    @Column(name="sub_division_id")
    public Integer getSubDivisionId() {
        return this.subDivisionId;
    }
    
    public void setSubDivisionId(Integer subDivisionId) {
        this.subDivisionId = subDivisionId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="creation_date", nullable=false, length=10)
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="period_from", nullable=false, length=10)
    public Date getPeriodFrom() {
        return this.periodFrom;
    }
    
    public void setPeriodFrom(Date periodFrom) {
        this.periodFrom = periodFrom;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="period_to", nullable=false, length=10)
    public Date getPeriodTo() {
        return this.periodTo;
    }
    
    public void setPeriodTo(Date periodTo) {
        this.periodTo = periodTo;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="due_date", nullable=false, length=10)
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    
    @Column(name="state")
    public Byte getState() {
        return this.state;
    }
    
    public void setState(Byte state) {
        this.state = state;
    }
    
    @Column(name="kpis", length=65535)
    public String getKpis() {
        return this.kpis;
    }
    
    public void setKpis(String kpis) {
        this.kpis = kpis;
    }




}


