package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProjectId generated by hbm2java
 */
@Embeddable
public class ProjectId  implements java.io.Serializable {


     private int projectId;
     private int customerId;

    public ProjectId() {
    }

    public ProjectId(int projectId, int customerId) {
       this.projectId = projectId;
       this.customerId = customerId;
    }
   

    @Column(name="project_id", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }

    @Column(name="customer_id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProjectId) ) return false;
		 ProjectId castOther = ( ProjectId ) other; 
         
		 return (this.getProjectId()==castOther.getProjectId())
 && (this.getCustomerId()==castOther.getCustomerId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProjectId();
         result = 37 * result + this.getCustomerId();
         return result;
   }   


}


