package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name="province"
    ,catalog="ashrm"
)
public class Province  implements java.io.Serializable {


     private Integer id;
     private String provinceName;
     private String provinceCode;
     private String couCode;

    public Province() {
    }

    public Province(String provinceName, String provinceCode, String couCode) {
       this.provinceName = provinceName;
       this.provinceCode = provinceCode;
       this.couCode = couCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="province_name", nullable=false, length=40)
    public String getProvinceName() {
        return this.provinceName;
    }
    
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }
    
    @Column(name="province_code", nullable=false, length=2)
    public String getProvinceCode() {
        return this.provinceCode;
    }
    
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }
    
    @Column(name="cou_code", nullable=false, length=2)
    public String getCouCode() {
        return this.couCode;
    }
    
    public void setCouCode(String couCode) {
        this.couCode = couCode;
    }




}


