package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RightsId generated by hbm2java
 */
@Embeddable
public class RightsId  implements java.io.Serializable {


     private String modId;
     private String usergId;

    public RightsId() {
    }

    public RightsId(String modId, String usergId) {
       this.modId = modId;
       this.usergId = usergId;
    }
   

    @Column(name="mod_id", nullable=false, length=36)
    public String getModId() {
        return this.modId;
    }
    
    public void setModId(String modId) {
        this.modId = modId;
    }

    @Column(name="userg_id", nullable=false, length=36)
    public String getUsergId() {
        return this.usergId;
    }
    
    public void setUsergId(String usergId) {
        this.usergId = usergId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RightsId) ) return false;
		 RightsId castOther = ( RightsId ) other; 
         
		 return ( (this.getModId()==castOther.getModId()) || ( this.getModId()!=null && castOther.getModId()!=null && this.getModId().equals(castOther.getModId()) ) )
 && ( (this.getUsergId()==castOther.getUsergId()) || ( this.getUsergId()!=null && castOther.getUsergId()!=null && this.getUsergId().equals(castOther.getUsergId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getModId() == null ? 0 : this.getModId().hashCode() );
         result = 37 * result + ( getUsergId() == null ? 0 : this.getUsergId().hashCode() );
         return result;
   }   


}


