package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Salarygrade generated by hbm2java
 */
@Entity
@Table(name="salarygrade"
    ,catalog="ashrm"
    , uniqueConstraints = @UniqueConstraint(columnNames="sal_grd_name") 
)
public class Salarygrade  implements java.io.Serializable {


     private String salGrdCode;
     private String salGrdName;
     private Set<EmpBasicsalary> empBasicsalaries = new HashSet<EmpBasicsalary>(0);
     private Set<JobTitle> jobTitles = new HashSet<JobTitle>(0);
     private Set<HsPrSalaryCurrencyDetail> hsPrSalaryCurrencyDetails = new HashSet<HsPrSalaryCurrencyDetail>(0);

    public Salarygrade() {
    }

	
    public Salarygrade(String salGrdCode) {
        this.salGrdCode = salGrdCode;
    }
    public Salarygrade(String salGrdCode, String salGrdName, Set<EmpBasicsalary> empBasicsalaries, Set<JobTitle> jobTitles, Set<HsPrSalaryCurrencyDetail> hsPrSalaryCurrencyDetails) {
       this.salGrdCode = salGrdCode;
       this.salGrdName = salGrdName;
       this.empBasicsalaries = empBasicsalaries;
       this.jobTitles = jobTitles;
       this.hsPrSalaryCurrencyDetails = hsPrSalaryCurrencyDetails;
    }
   
     @Id 
    
    @Column(name="sal_grd_code", unique=true, nullable=false, length=13)
    public String getSalGrdCode() {
        return this.salGrdCode;
    }
    
    public void setSalGrdCode(String salGrdCode) {
        this.salGrdCode = salGrdCode;
    }
    
    @Column(name="sal_grd_name", unique=true, length=60)
    public String getSalGrdName() {
        return this.salGrdName;
    }
    
    public void setSalGrdName(String salGrdName) {
        this.salGrdName = salGrdName;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="salarygrade")
    public Set<EmpBasicsalary> getEmpBasicsalaries() {
        return this.empBasicsalaries;
    }
    
    public void setEmpBasicsalaries(Set<EmpBasicsalary> empBasicsalaries) {
        this.empBasicsalaries = empBasicsalaries;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="salarygrade")
    public Set<JobTitle> getJobTitles() {
        return this.jobTitles;
    }
    
    public void setJobTitles(Set<JobTitle> jobTitles) {
        this.jobTitles = jobTitles;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="salarygrade")
    public Set<HsPrSalaryCurrencyDetail> getHsPrSalaryCurrencyDetails() {
        return this.hsPrSalaryCurrencyDetails;
    }
    
    public void setHsPrSalaryCurrencyDetails(Set<HsPrSalaryCurrencyDetail> hsPrSalaryCurrencyDetails) {
        this.hsPrSalaryCurrencyDetails = hsPrSalaryCurrencyDetails;
    }




}


