package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Skill generated by hbm2java
 */
@Entity
@Table(name="skill"
    ,catalog="ashrm"
)
public class Skill  implements java.io.Serializable {


     private String skillCode;
     private String skillName;
     private String skillDescription;

    public Skill() {
    }

	
    public Skill(String skillCode) {
        this.skillCode = skillCode;
    }
    public Skill(String skillCode, String skillName, String skillDescription) {
       this.skillCode = skillCode;
       this.skillName = skillName;
       this.skillDescription = skillDescription;
    }
   
     @Id 
    
    @Column(name="skill_code", unique=true, nullable=false, length=13)
    public String getSkillCode() {
        return this.skillCode;
    }
    
    public void setSkillCode(String skillCode) {
        this.skillCode = skillCode;
    }
    
    @Column(name="skill_name", length=120)
    public String getSkillName() {
        return this.skillName;
    }
    
    public void setSkillName(String skillName) {
        this.skillName = skillName;
    }
    
    @Column(name="skill_description", length=65535)
    public String getSkillDescription() {
        return this.skillDescription;
    }
    
    public void setSkillDescription(String skillDescription) {
        this.skillDescription = skillDescription;
    }




}


