package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TimesheetSubmissionPeriod generated by hbm2java
 */
@Entity
@Table(name="timesheet_submission_period"
    ,catalog="ashrm"
)
public class TimesheetSubmissionPeriod  implements java.io.Serializable {


     private int timesheetPeriodId;
     private String name;
     private int frequency;
     private Integer period;
     private Integer startDay;
     private Integer endDay;
     private String description;
     private Set<Timesheet> timesheets = new HashSet<Timesheet>(0);
     private Set<Employee> employees = new HashSet<Employee>(0);

    public TimesheetSubmissionPeriod() {
    }

	
    public TimesheetSubmissionPeriod(int timesheetPeriodId, int frequency) {
        this.timesheetPeriodId = timesheetPeriodId;
        this.frequency = frequency;
    }
    public TimesheetSubmissionPeriod(int timesheetPeriodId, String name, int frequency, Integer period, Integer startDay, Integer endDay, String description, Set<Timesheet> timesheets, Set<Employee> employees) {
       this.timesheetPeriodId = timesheetPeriodId;
       this.name = name;
       this.frequency = frequency;
       this.period = period;
       this.startDay = startDay;
       this.endDay = endDay;
       this.description = description;
       this.timesheets = timesheets;
       this.employees = employees;
    }
   
     @Id 
    
    @Column(name="timesheet_period_id", unique=true, nullable=false)
    public int getTimesheetPeriodId() {
        return this.timesheetPeriodId;
    }
    
    public void setTimesheetPeriodId(int timesheetPeriodId) {
        this.timesheetPeriodId = timesheetPeriodId;
    }
    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="frequency", nullable=false)
    public int getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(int frequency) {
        this.frequency = frequency;
    }
    
    @Column(name="period")
    public Integer getPeriod() {
        return this.period;
    }
    
    public void setPeriod(Integer period) {
        this.period = period;
    }
    
    @Column(name="start_day")
    public Integer getStartDay() {
        return this.startDay;
    }
    
    public void setStartDay(Integer startDay) {
        this.startDay = startDay;
    }
    
    @Column(name="end_day")
    public Integer getEndDay() {
        return this.endDay;
    }
    
    public void setEndDay(Integer endDay) {
        this.endDay = endDay;
    }
    
    @Column(name="description", length=250)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="timesheetSubmissionPeriod")
    public Set<Timesheet> getTimesheets() {
        return this.timesheets;
    }
    
    public void setTimesheets(Set<Timesheet> timesheets) {
        this.timesheets = timesheets;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="employee_timesheet_period", catalog="ashrm", joinColumns = { 
        @JoinColumn(name="timesheet_period_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="employee_id", nullable=false, updatable=false) })
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


