package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Timesheet generated by hbm2java
 */
@Entity
@Table(name="timesheet"
    ,catalog="ashrm"
)
public class Timesheet  implements java.io.Serializable {


     private TimesheetId id;
     private Employee employee;
     private TimesheetSubmissionPeriod timesheetSubmissionPeriod;
     private Date startDate;
     private Date endDate;
     private Integer status;
     private String comment;
     private Set<TimeEvent> timeEvents = new HashSet<TimeEvent>(0);

    public Timesheet() {
    }

	
    public Timesheet(TimesheetId id, Employee employee, TimesheetSubmissionPeriod timesheetSubmissionPeriod) {
        this.id = id;
        this.employee = employee;
        this.timesheetSubmissionPeriod = timesheetSubmissionPeriod;
    }
    public Timesheet(TimesheetId id, Employee employee, TimesheetSubmissionPeriod timesheetSubmissionPeriod, Date startDate, Date endDate, Integer status, String comment, Set<TimeEvent> timeEvents) {
       this.id = id;
       this.employee = employee;
       this.timesheetSubmissionPeriod = timesheetSubmissionPeriod;
       this.startDate = startDate;
       this.endDate = endDate;
       this.status = status;
       this.comment = comment;
       this.timeEvents = timeEvents;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="timesheetId", column=@Column(name="timesheet_id", nullable=false) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="employee_id", nullable=false) ), 
        @AttributeOverride(name="timesheetPeriodId", column=@Column(name="timesheet_period_id", nullable=false) ) } )
    public TimesheetId getId() {
        return this.id;
    }
    
    public void setId(TimesheetId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false, insertable=false, updatable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="timesheet_period_id", nullable=false, insertable=false, updatable=false)
    public TimesheetSubmissionPeriod getTimesheetSubmissionPeriod() {
        return this.timesheetSubmissionPeriod;
    }
    
    public void setTimesheetSubmissionPeriod(TimesheetSubmissionPeriod timesheetSubmissionPeriod) {
        this.timesheetSubmissionPeriod = timesheetSubmissionPeriod;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date", length=19)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date", length=19)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    @Column(name="status")
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    @Column(name="comment", length=250)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="timesheet")
    public Set<TimeEvent> getTimeEvents() {
        return this.timeEvents;
    }
    
    public void setTimeEvents(Set<TimeEvent> timeEvents) {
        this.timeEvents = timeEvents;
    }




}


