package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UniqueId generated by hbm2java
 */
@Entity
@Table(name="unique_id"
    ,catalog="ashrm"
    , uniqueConstraints = @UniqueConstraint(columnNames={"table_name", "field_name"}) 
)
public class UniqueId  implements java.io.Serializable {


     private Integer id;
     private int lastId;
     private String tableName;
     private String fieldName;

    public UniqueId() {
    }

    public UniqueId(int lastId, String tableName, String fieldName) {
       this.lastId = lastId;
       this.tableName = tableName;
       this.fieldName = fieldName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="last_id", nullable=false)
    public int getLastId() {
        return this.lastId;
    }
    
    public void setLastId(int lastId) {
        this.lastId = lastId;
    }
    
    @Column(name="table_name", nullable=false, length=50)
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    
    @Column(name="field_name", nullable=false, length=50)
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }




}


