package Model;
// Generated Jan 14, 2011 3:39:55 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Workshift generated by hbm2java
 */
@Entity
@Table(name="workshift"
    ,catalog="ashrm"
)
public class Workshift  implements java.io.Serializable {


     private int workshiftId;
     private String name;
     private BigDecimal hoursPerDay;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Workshift() {
    }

	
    public Workshift(int workshiftId, String name, BigDecimal hoursPerDay) {
        this.workshiftId = workshiftId;
        this.name = name;
        this.hoursPerDay = hoursPerDay;
    }
    public Workshift(int workshiftId, String name, BigDecimal hoursPerDay, Set<Employee> employees) {
       this.workshiftId = workshiftId;
       this.name = name;
       this.hoursPerDay = hoursPerDay;
       this.employees = employees;
    }
   
     @Id 
    
    @Column(name="workshift_id", unique=true, nullable=false)
    public int getWorkshiftId() {
        return this.workshiftId;
    }
    
    public void setWorkshiftId(int workshiftId) {
        this.workshiftId = workshiftId;
    }
    
    @Column(name="name", nullable=false, length=250)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="hours_per_day", nullable=false, precision=4)
    public BigDecimal getHoursPerDay() {
        return this.hoursPerDay;
    }
    
    public void setHoursPerDay(BigDecimal hoursPerDay) {
        this.hoursPerDay = hoursPerDay;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="employee_workshift", catalog="ashrm", joinColumns = { 
        @JoinColumn(name="workshift_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="emp_number", nullable=false, updatable=false) })
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


